### ISSUE TITLE
"no such table: recipes_nestings_resolved" after upgrading

### ISSUE THREAD

**Issue by Forceu** [grocy/grocy#103]
After upgrading using the update.sh script the tab Recipes cannot be opened anymore, as the table "recipes_nestings_resolved" was not created during the upgrade.

```
Slim Application Error
The application could not run because of the following error:

Details
Type: PDOException
Code: HY000
Message: SQLSTATE[HY000]: General error: 1 no such table: recipes_nestings_resolved
File: /var/www/grocy/vendor/morris/lessql/src/LessQL/Database.php
Line: 117
Trace
#0 /var/www/grocy/vendor/morris/lessql/src/LessQL/Database.php(117): PDO->prepare('SELECT * FROM `...')
#1 /var/www/grocy/vendor/morris/lessql/src/LessQL/Database.php(529): LessQL\Database->prepare('SELECT * FROM `...')
#2 /var/www/grocy/vendor/morris/lessql/src/LessQL/Result.php(162): LessQL\Database->select('recipes', Array)
#3 /var/www/grocy/vendor/morris/lessql/src/LessQL/Result.php(378): LessQL\Result->execute()
#4 /var/www/grocy/controllers/RecipesController.php(38): LessQL\Result->fetchAll()
#5 [internal function]: Grocy\Controllers\RecipesController->Overview(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#6 /var/www/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#7 /var/www/grocy/vendor/slim/slim/Slim/Route.php(356): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#8 /var/www/grocy/middleware/SessionAuthMiddleware.php(57): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#9 [internal function]: Grocy\Middleware\SessionAuthMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#10 /var/www/grocy/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Grocy\Middleware\SessionAuthMiddleware), Array)
#11 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#12 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#13 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#14 /var/www/grocy/vendor/slim/slim/Slim/Route.php(334): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#15 /var/www/grocy/vendor/slim/slim/Slim/App.php(515): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#16 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#17 /var/www/grocy/vendor/slim/slim/Slim/App.php(406): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#18 /var/www/grocy/vendor/slim/slim/Slim/App.php(314): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#19 /var/www/grocy/app.php(71): Slim\App->run()
#20 /var/www/grocy/public/index.php(3): require_once('/var/www/grocy/...')
#21 {main}
```

**Comment by berrnd** [comment]
Cannot reproduce this, `recipes_nestings_resolved` is a new VIEW created in [migration 43](https://github.com/grocy/grocy/blob/b84e6da0ddac55e33d8e9caccf0ab81f1fb041f6/migrations/0043.sql), migrations are done when visiting the root route (`/`) (also [mentioned in README](https://github.com/grocy/grocy#database-migrations)) - have you maybe directly opened the `/recipes` page?

**Comment by berrnd** [comment]
The view is in the database, client cache is not involved in this...

Maybe you just visited `/` in the meantime - as said, database migrations are only done on this route in the background...
