### ISSUE TITLE
CentOS7 - PHP 7.2 - SQLSTATE[HY000]: General error: 1 near "WITH": syntax error

### ISSUE THREAD

**Issue by theone85ca** [grocy/grocy#104]
Hey,

I'm not sure how to tackle this one. I'm running an updated CentOS 7 build with PHP 7.2 installed. However, when the loading the root domain for grocy I encounter the following error.

```
Type: PDOException
Code: HY000
Message: SQLSTATE[HY000]: General error: 1 near "WITH": syntax error
File: /var/www/html/services/DatabaseService.php
Line: 45
Trace

#0 /var/www/html/services/DatabaseService.php(45): PDO->exec('CREATE TABLE re...')
#1 /var/www/html/services/DatabaseMigrationService.php(47): Grocy\Services\DatabaseService->ExecuteDbStatement('CREATE TABLE re...')
#2 /var/www/html/services/DatabaseMigrationService.php(23): Grocy\Services\DatabaseMigrationService->ExecuteSqlMigrationWhenNeeded(43, 'CREATE TABLE re...')
#3 /var/www/html/controllers/LoginController.php(70): Grocy\Services\DatabaseMigrationService->MigrateDatabase()
#4 [internal function]: Grocy\Controllers\LoginController->Root(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#5 /var/www/html/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#6 /var/www/html/vendor/slim/slim/Slim/Route.php(356): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#7 /var/www/html/middleware/SessionAuthMiddleware.php(26): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#8 [internal function]: Grocy\Middleware\SessionAuthMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#9 /var/www/html/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Grocy\Middleware\SessionAuthMiddleware), Array)
#10 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#11 /var/www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#12 /var/www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#13 /var/www/html/vendor/slim/slim/Slim/Route.php(334): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#14 /var/www/html/vendor/slim/slim/Slim/App.php(515): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#15 /var/www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#16 /var/www/html/vendor/slim/slim/Slim/App.php(406): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#17 /var/www/html/vendor/slim/slim/Slim/App.php(314): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#18 /var/www/html/app.php(71): Slim\App->run()
#19 /var/www/html/public/index.php(3): require_once('/var/www/html/a...')
#20 {main}
```

Refreshing the page results in a slightly different error that seems to stick. This second error refers to an entry in the database already being there. Looks like fixing the above might fix the latter.

Thanks for any help!

**Comment by berrnd** [comment]
Checked [migration 43](https://github.com/grocy/grocy/blob/master/migrations/0043.sql) again and found no problem...

Only thing I can imagine is that you maybe use SQLite < [3.8.3](https://www.sqlite.org/releaselog/3_8_3.html) - common table expressions (which are used in that migration) are only supported since then...

**Comment by theone85ca** [comment]
That could very well be the issue.
CentOS 7 does not support 3.8.3 afaik

**Comment by berrnd** [comment]
Ok, it's over 4 years since this SQLite release, but will mention this in README...

Feel free to reopen this issue if this was not the problem at the end.

**Comment by bendauphinee** [comment]
Might be worth adding a prerequisite check script that runs before anything else to make sure the server has the right versions of everything. I've run into the same issue, and it took me a few minutes to locate this thread via Google. CentOS 7, SQLite 3.7.17

**Comment by berrnd** [comment]
It's also mentioned in the projects [README](https://github.com/grocy/grocy#how-to-install), but ok, let's add this to new PrerequisiteChecker (#639), created #805 to track this.
