### ISSUE TITLE
404 when running with php -S

### ISSUE THREAD

**Issue by basxto** [grocy/grocy#1041]
I just get a 404, when I run grocy with `php -S 0.0.0.0:8000 -n -dextension=gd.so -dextension=pdo_sqlite.so -t /usr/share/webapps/grocy/public/`

I activated `DISABLE_URL_REWRITING` in `data/config.php`

I called it as `http://192.168.212.179:8000/index.php`

```
404 Not Found

The application could not run because of the following error:
Details
Type: Slim\Exception\HttpNotFoundException
Code: 404
Message: Not found.
File: /usr/share/webapps/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php
Line: 93
Trace

#0 /usr/share/webapps/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Slim\Middleware\RoutingMiddleware->performRouting(Object(Slim\Http\ServerRequest))
#1 /usr/share/webapps/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\RoutingMiddleware->process(Object(Slim\Http\ServerRequest), Object(Slim\Routing\RouteRunner))
#2 /usr/share/webapps/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#3 /usr/share/webapps/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\ErrorMiddleware->process(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#4 /usr/share/webapps/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#5 /usr/share/webapps/grocy/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#6 /usr/share/webapps/grocy/vendor/slim/slim/Slim/App.php(199): Slim\App->handle(Object(Slim\Http\ServerRequest))
#7 /usr/share/webapps/grocy/app.php(68): Slim\App->run()
#8 /usr/share/webapps/grocy/public/index.php(27): require_once('/usr/share/weba...')
#9 {main}

Go Back
```

**Comment by berrnd** [comment]
Please use the [subreddit](https://www.reddit.com/r/grocy/) for questions/help requests (as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests)), this is the issue tracker.

It should work like that, I also run it so for development - but if you disabled URL rewriting (however, PHP can handle this), the main/root URL is `http://192.168.212.179:8000/index.php/` (not the trailing slash).

**Comment by basxto** [comment]
Thanks, it helps a lot knowing, that it basically works with `php -S`.
