### ISSUE TITLE
Cannot run current master

### ISSUE THREAD

**Issue by MrJohnZoidberg** [grocy/grocy#1095]
I just wanted to try out the current master on my server, but I cannot see the website, always a nginx error message:

```
2020/10/25 14:20:09 [error] 20583#0: *179 FastCGI sent in stderr: "PHP message: PHP Warning:  Use of undefined constant GROCY_LOCALE - assumed 'GROCY_LOCALE' (this will throw an Error in a future version of PHP) in /var/www/grocy-dev/controllers/BaseController.php on line 73PHP message: PHP Fatal error:  Uncaught InvalidArgumentException: '/var/www/grocy-dev/services/../localization/GROCY_LOCALE/strings.po' is not a valid file in /var/www/grocy-dev/vendor/gettext/gettext/src/Extractors/Extractor.php:37
Stack trace:
#0 /var/www/grocy-dev/vendor/gettext/gettext/src/Extractors/Extractor.php(16): Gettext\Extractors\Extractor::getFiles('/var/www/grocy-...')
#1 [internal function]: Gettext\Extractors\Extractor::fromFile('/var/www/grocy-...', Object(Gettext\Translations), Array)
#2 /var/www/grocy-dev/vendor/gettext/gettext/src/Translations.php(182): call_user_func('Gettext\\Extract...', '/var/www/grocy-...', Object(Gettext\Translations), Array)
#3 [internal function]: Gettext\Translations->__call('addFromPoFile', Array)
#4 /var/www/grocy-dev/vendor/gettext/gettext/src/Translations.php(161): call_user_func_array(Array, Array)
#5 /var/www/grocy-dev/services/LocalizationService.php(139): Gettext\Translations::__callStatic('fromPoFile', Array)
#6 /var/www/grocy-dev/services/Loc" while reading response header from upstream, client: 1.2.3.4, server: grocy-dev.mydomain.com, request: "GET /poweredby.png HTTP/2.0", upstream: "fastcgi://unix:/var/run/php-fpm/www.sock:", host: "grocy-dev.mydomain.com", referrer: "https://grocy-dev.mydomain.com/"
```

Am I doing something wrong?

**Comment by berrnd** [comment]
Cannot reproduce this, also had that some time before, but not with the current state of the master branch...

It's about that `GROCY_LOCALE` is not defined, which is done in `app.php` and `LocaleMiddleware.php`, fallback is always the `config.php` setting `DEFAULT_LOCALE` - so make sure that this exist.

**Comment by MrJohnZoidberg** [comment]
Ah, now I have the culprit: SELinux :smile:

I had to execute the following command to apply my rule `fcontext -a -f a -t httpd_sys_rw_content_t -r 's0' '/var/www/grocy-dev/data(/.*)?'` to the cloned repo:

`sudo restorecon -vR *`
