### ISSUE TITLE
Bug: Unable to start Grocy after update, SQL error

### ISSUE THREAD

**Issue by Forceu** [grocy/grocy#1205]
After updating from 2.7.1 to 3.0.0 with the update.sh script

Error source:
```
/var/www/grocy/services/DatabaseService.php:33
```

Error message:
```
SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: product_barcodes.barcode
```

Stack trace:
```
#0 /var/www/grocy/services/DatabaseService.php(33): PDO->exec('-- Delete stock...')
#1 /var/www/grocy/services/DatabaseMigrationService.php(56): Grocy\Services\DatabaseService->ExecuteDbStatement('-- Delete stock...')
#2 /var/www/grocy/services/DatabaseMigrationService.php(30): Grocy\Services\DatabaseMigrationService->ExecuteSqlMigrationWhenNeeded(103, '-- Delete stock...')
#3 /var/www/grocy/controllers/SystemController.php(27): Grocy\Services\DatabaseMigrationService->MigrateDatabase()
#4 /var/www/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\Controllers\SystemController->Root(Object(Slim\Http\ServerRequest), Object(Slim\Http\Response), Array)
#5 /var/www/grocy/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\ServerRequest), Object(Slim\Http\Response), Array)
#6 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle(Object(Slim\Http\ServerRequest))
#7 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#8 /var/www/grocy/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#9 /var/www/grocy/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run(Object(Slim\Http\ServerRequest))
#10 /var/www/grocy/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle(Object(Slim\Http\ServerRequest))
#11 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\LocaleMiddleware->__invoke(Object(Slim\Http\ServerRequest), Object(Slim\Routing\RouteRunner))
#12 /var/www/grocy/middleware/AuthMiddleware.php(31): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#13 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\AuthMiddleware->__invoke(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#14 /var/www/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#15 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#16 /var/www/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#17 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#18 /var/www/grocy/middleware/CorsMiddleware.php(30): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#19 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\CorsMiddleware->__invoke(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#20 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#21 /var/www/grocy/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#22 /var/www/grocy/vendor/slim/slim/Slim/App.php(199): Slim\App->handle(Object(Slim\Http\ServerRequest))
#23 /var/www/grocy/app.php(77): Slim\App->run()
#24 /var/www/grocy/public/index.php(45): require_once('/var/www/grocy/...')
#25 {main}
```

**Comment by berrnd** [comment]
Thanks for finding that.

Most probably your product barcodes are not unique.

Please restore your backup for this - will add a check and re-publish v3.0.0 shortly.

**Comment by berrnd** [comment]
Having duplicate barcodes (means the same barcode attached to multiple products) is now possible again (because it was also possible before, but most probably still makes not so much sense...).

v3.0.0 is re-published with this fix included.

**Comment by Forceu** [comment]
Thanks I just had a look at the db, apparently I had one product that that the same barcode twice (eg. "1234,1234"). I think that was caused by an old BarcodeBuddy version.

**Comment by berrnd** [comment]
The question would be which product should keep the duplicate barcode...

On looking up a barcode via the UI, it currently takes the first found product in alphabetical order.

**Comment by Forceu** [comment]
In that case it should do the same, because you are absolutely right that it does not make sense to have duplicate barcodes. In this case it was caused by an old bug in a 3rd party software, I don't think that anyone has duplicate barcodes on purpose.
