### ISSUE TITLE
Bug: Call to undefined function ctype_space() | Update to v3.0.0

### ISSUE THREAD

**Issue by edenhaus** [grocy/grocy#1207]
Running the latest linuxserver/grocy container

Error source:
```
/app/grocy/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Token/Text.php:43
```

Error message:
```
Call to undefined function ctype_space()
```

Stack trace:
```
#0 /app/grocy/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Lexer/DirectLex.php(158): HTMLPurifier_Token_Text->__construct('robert')
#1 /app/grocy/vendor/ezyang/htmlpurifier/library/HTMLPurifier.php(213): HTMLPurifier_Lexer_DirectLex->tokenizeHTML('robert', Object(HTMLPurifier_Config), Object(HTMLPurifier_Context))
#2 /app/grocy/controllers/BaseController.php(205): HTMLPurifier->purify('robert')
#3 /app/grocy/controllers/LoginController.php(28): Grocy\Controllers\BaseController->GetParsedAndFilteredRequestBody(Object(Slim\Http\ServerRequest))
#4 /app/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\Controllers\LoginController->ProcessLogin(Object(Slim\Http\ServerRequest), Object(Slim\Http\Response), Array)
#5 /app/grocy/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\ServerRequest), Object(Slim\Http\Response), Array)
#6 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle(Object(Slim\Http\ServerRequest))
#7 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#8 /app/grocy/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#9 /app/grocy/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run(Object(Slim\Http\ServerRequest))
#10 /app/grocy/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle(Object(Slim\Http\ServerRequest))
#11 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\LocaleMiddleware->__invoke(Object(Slim\Http\ServerRequest), Object(Slim\Routing\RouteRunner))
#12 /app/grocy/middleware/AuthMiddleware.php(36): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#13 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\AuthMiddleware->__invoke(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#14 /app/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#15 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#16 /app/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#17 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#18 /app/grocy/middleware/CorsMiddleware.php(30): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#19 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\CorsMiddleware->__invoke(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#20 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#21 /app/grocy/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#22 /app/grocy/vendor/slim/slim/Slim/App.php(199): Slim\App->handle(Object(Slim\Http\ServerRequest))
#23 /app/grocy/app.php(77): Slim\App->run()
#24 /app/grocy/public/index.php(45): require_once('/app/grocy/app....')
#25 {main}
```

`robert` is my username

**Comment by Forceu** [comment]
This is an issue with the docker build, the related issue is here: https://github.com/linuxserver/docker-grocy/issues/26

To manually fix it for now, execute `docker exec -it CONTAINER-NAME apk add php7-ctype` and restart the container

**Comment by edenhaus** [comment]
Oh thanks 😊
