### ISSUE TITLE
Bug: Never show on stock overview - checkbox should be unchecked on default

### ISSUE THREAD

**Issue by fnordson** [grocy/grocy#1212]
Verion: 3.0.0. (checked on demo) 

When adding a new product, the checkbox "Never show on stock overview" is checked. 
I don't see why this should be the default. I only just realized it was when I couldn't find the products I just entered on the list. 

![grafik](https://user-images.githubusercontent.com/5624605/102918119-a5a08900-4486-11eb-9f40-7ca04fb056a3.png)

**Comment by berrnd** [comment]
For those who want to have this now:

Replace the file `views/productform.blade.php` with [that one](https://github.com/grocy/grocy/blob/cf05be35fe583037074530b696c18bde998363f9/views/productform.blade.php).

**Comment by fnordson** [comment]
> 
> 
> For those who want to have this now:
> 
> Replace the file `views/productform.blade.php` with [that one](https://github.com/grocy/grocy/blob/cf05be35fe583037074530b696c18bde998363f9/views/productform.blade.php).

I did replace the file and now adding a new product on /products gives me the following error 
(**(URL & HOMEURL replaced by me)**):

Error source:
```
URL/data/viewcache/de032629fd87a3874a896e1d6be9ddea22f9f5d2.php:1160
```

Error message:
```
syntax error, unexpected ':', expecting '(' (View: URL/views/productform.blade.php)
```

Stack trace:
```
#0 URL/vendor/illuminate/view/Engines/PhpEngine.php(47): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(Symfony\Component\Debug\Exception\FatalThrowableError), 1)
#1 URL/vendor/illuminate/view/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('HOMEURL/...', Array)
#2 URL/vendor/illuminate/view/View.php(142): Illuminate\View\Engines\CompilerEngine->get('HOMEURL/...', Array)
#3 URL/vendor/illuminate/view/View.php(125): Illuminate\View\View->getContents()
#4 URL/vendor/illuminate/view/View.php(90): Illuminate\View\View->renderContents()
#5 URL/vendor/rubellum/slim-blade-view/src/Blade.php(173): Illuminate\View\View->render()
#6 URL/vendor/rubellum/slim-blade-view/src/Blade.php(65): Slim\Views\Blade->fetch('productform', Array)
#7 URL/controllers/BaseController.php(162): Slim\Views\Blade->render(Object(Slim\Http\Response), 'productform', Array)
#8 URL/controllers/BaseController.php(186): Grocy\Controllers\BaseController->render(Object(Slim\Http\Response), 'productform', Array)
#9 URL/controllers/StockController.php(148): Grocy\Controllers\BaseController->renderPage(Object(Slim\Http\Response), 'productform', Array)
#10 URL/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\Controllers\StockController->ProductEditForm(Object(Slim\Http\ServerRequest), Object(Slim\Http\Response), Array)
#11 URL/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\ServerRequest), Object(Slim\Http\Response), Array)
#12 URL/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle(Object(Slim\Http\ServerRequest))
#13 URL/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#14 URL/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#15 URL/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run(Object(Slim\Http\ServerRequest))
#16 URL/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle(Object(Slim\Http\ServerRequest))
#17 URL/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\LocaleMiddleware->__invoke(Object(Slim\Http\ServerRequest), Object(Slim\Routing\RouteRunner))
#18 URL/middleware/AuthMiddleware.php(76): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#19 URL/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\AuthMiddleware->__invoke(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#20 URL/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#21 URL/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#22 URL/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#23 URL/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#24 URL/middleware/CorsMiddleware.php(30): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#25 URL/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\CorsMiddleware->__invoke(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#26 URL/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#27 URL/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#28 URL/vendor/slim/slim/Slim/App.php(199): Slim\App->handle(Object(Slim\Http\ServerRequest))
#29 URL/app.php(77): Slim\App->run()
#30 URL/public/index.php(45): require_once('HOMEURL/...')
#31 {main}
```

**Comment by berrnd** [comment]
Can't reproduce this - how have you changed/downloaded the file?

You should just download the "raw" file, the following link, just use your browsers "Save as" function (I have also updated the link above to point to the raw file if this was maybe too unclear...):

![grafik](https://user-images.githubusercontent.com/2161815/103175331-83817f00-4869-11eb-8a29-46085929d39e.png)


https://raw.githubusercontent.com/grocy/grocy/cf05be35fe583037074530b696c18bde998363f9/views/productform.blade.php

**Comment by fnordson** [comment]
I just "save as"'d it. 
So I guess this was the issue. 
Need to check the other two for the barcode issue ;) 

Thanks.
