### ISSUE TITLE
Bug:  Argument #1 ($var) must be of type Countable|array, null given

### ISSUE THREAD

**Issue by syphernl** [grocy/grocy#1220]
Adding (new) ingredients to a new recipe results in a fatal error.

Reproduce:

- Add a new recipe
- After creating the recipe, add the ingredients
- Enter a product name that doesn't already exist
- Once you switch form fields, a popup asks to create as new product / add barcode etc
- Choose Add as new product

A server-error will be given:

Error source:
```
/var/www/clients/client2/web7/web/data/viewcache/8b784c596b284afc4092408f4f0b899096187ff5.php:1
```

Error message:
```
count(): Argument #1 ($var) must be of type Countable|array, null given (View: /var/www/clients/client2/web7/web/views/components/userfields_thead.blade.php) (View: /var/www/clients/client2/web7/web/views/components/userfields_thead.blade.php)
```

Stack trace:
```
#0 /var/www/clients/client2/web7/web/vendor/illuminate/view/Engines/PhpEngine.php(45): Illuminate\View\Engines\CompilerEngine->handleViewException()
#1 /var/www/clients/client2/web7/web/vendor/illuminate/view/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath()
#2 /var/www/clients/client2/web7/web/vendor/illuminate/view/View.php(142): Illuminate\View\Engines\CompilerEngine->get()
#3 /var/www/clients/client2/web7/web/vendor/illuminate/view/View.php(125): Illuminate\View\View->getContents()
#4 /var/www/clients/client2/web7/web/vendor/illuminate/view/View.php(90): Illuminate\View\View->renderContents()
#5 /var/www/clients/client2/web7/web/vendor/rubellum/slim-blade-view/src/Blade.php(173): Illuminate\View\View->render()
#6 /var/www/clients/client2/web7/web/vendor/rubellum/slim-blade-view/src/Blade.php(65): Slim\Views\Blade->fetch()
#7 /var/www/clients/client2/web7/web/controllers/BaseController.php(162): Slim\Views\Blade->render()
#8 /var/www/clients/client2/web7/web/controllers/BaseController.php(186): Grocy\Controllers\BaseController->render()
#9 /var/www/clients/client2/web7/web/controllers/StockController.php(148): Grocy\Controllers\BaseController->renderPage()
#10 /var/www/clients/client2/web7/web/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\Controllers\StockController->ProductEditForm()
#11 /var/www/clients/client2/web7/web/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
#12 /var/www/clients/client2/web7/web/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#13 /var/www/clients/client2/web7/web/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
#14 /var/www/clients/client2/web7/web/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#15 /var/www/clients/client2/web7/web/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#16 /var/www/clients/client2/web7/web/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#17 /var/www/clients/client2/web7/web/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\LocaleMiddleware->__invoke()
#18 /var/www/clients/client2/web7/web/middleware/AuthMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /var/www/clients/client2/web7/web/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\AuthMiddleware->__invoke()
#20 /var/www/clients/client2/web7/web/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /var/www/clients/client2/web7/web/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#22 /var/www/clients/client2/web7/web/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#23 /var/www/clients/client2/web7/web/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#24 /var/www/clients/client2/web7/web/middleware/CorsMiddleware.php(30): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#25 /var/www/clients/client2/web7/web/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\CorsMiddleware->__invoke()
#26 /var/www/clients/client2/web7/web/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#27 /var/www/clients/client2/web7/web/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#28 /var/www/clients/client2/web7/web/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#29 /var/www/clients/client2/web7/web/app.php(77): Slim\App->run()
#30 /var/www/clients/client2/web7/web/public/index.php(45): require_once('...')
#31 {main}
```

This also occurs directly when opening `/product/new`

**Comment by syphernl** [comment]
This seems to be happening on PHP8.0 only, it works fine on PHP7.4.13

**Comment by berrnd** [comment]
> This seems to be happening on PHP8.0 only, it works fine on PHP7.4.13

Sorry, but grocy is currently supposed to run with PHP 7.4 (and a pretty up to date SQLite version) while it's user-reported that PHP 7.2 and SQLite 3.9.0 is also fine ([ref](https://github.com/grocy/grocy#how-to-install)).

**Comment by berrnd** [comment]
Just to note that also here: PHP 8 will be supported in the next release (ref https://github.com/grocy/grocy/commit/b0d38b87de07f4ae117dd7e8e437aac2e8d842b1).
