### ISSUE TITLE
Bug: General error: 1 no such column: p.due_type (View: /var/www/grocy/views/stockoverview.blade.php)

### ISSUE THREAD

**Issue by moverperfect** [grocy/grocy#1288]
Getting this message when opening Stock overview after updating to v3.0.1

I'm assuming that if I open the db file and manually add  due_type column this should be fixed?

Error source:
```
/var/www/grocy/vendor/morris/lessql/src/LessQL/Database.php:108
```

Error message:
```
SQLSTATE[HY000]: General error: 1 no such column: p.due_type (View: /var/www/grocy/views/stockoverview.blade.php)
```

Stack trace:
```
#0 /var/www/grocy/vendor/illuminate/view/Engines/PhpEngine.php(45): Illuminate\View\Engines\CompilerEngine->handleViewException()
#1 /var/www/grocy/vendor/illuminate/view/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath()
#2 /var/www/grocy/vendor/illuminate/view/View.php(142): Illuminate\View\Engines\CompilerEngine->get()
#3 /var/www/grocy/vendor/illuminate/view/View.php(125): Illuminate\View\View->getContents()
#4 /var/www/grocy/vendor/illuminate/view/View.php(90): Illuminate\View\View->renderContents()
#5 /var/www/grocy/vendor/rubellum/slim-blade-view/src/Blade.php(173): Illuminate\View\View->render()
#6 /var/www/grocy/vendor/rubellum/slim-blade-view/src/Blade.php(65): Slim\Views\Blade->fetch()
#7 /var/www/grocy/controllers/BaseController.php(173): Slim\Views\Blade->render()
#8 /var/www/grocy/controllers/BaseController.php(196): Grocy\Controllers\BaseController->render()
#9 /var/www/grocy/controllers/StockController.php(96): Grocy\Controllers\BaseController->renderPage()
#10 /var/www/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\Controllers\StockController->Overview()
#11 /var/www/grocy/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
#12 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#13 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
#14 /var/www/grocy/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#15 /var/www/grocy/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#16 /var/www/grocy/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#17 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\LocaleMiddleware->__invoke()
#18 /var/www/grocy/middleware/AuthMiddleware.php(76): class@anonymous->handle()
#19 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\AuthMiddleware->__invoke()
#20 /var/www/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): class@anonymous->handle()
#21 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#22 /var/www/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle()
#23 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#24 /var/www/grocy/middleware/CorsMiddleware.php(30): class@anonymous->handle()
#25 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\CorsMiddleware->__invoke()
#26 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle()
#27 /var/www/grocy/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#28 /var/www/grocy/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#29 /var/www/grocy/app.php(94): Slim\App->run()
#30 /var/www/grocy/public/index.php(45): require_once('/var/www/grocy/...')
#31 {main}
```

**Comment by berrnd** [comment]
> I'm assuming that if I open the db file and manually add due_type column this should be fixed?

Maybe.

This is most probably caused by that you didn't ONLY use releases or a (very old) SQLite version.

SQLite < 3.9.0 doesn't work and migrations only work between released versions, not when using the master branch (at any point). Related to #1209.
