### ISSUE TITLE
Bug: Checking "Track date only" on a chore causes ical feed to crash

### ISSUE THREAD

**Issue by redinsight** [grocy/grocy#1547]
If a chore is created or modified to have the _Track date only_ checkbox checked the ical feed seems to break. It was happening on my local copy of 3.1.0 so I went to the demo site [here](https://en.demo.grocy.info/) and was able to replicate by ticking the Track date only checkbox on a chore and then the ical feed started crashing on the demo as well when accessed. If no chores have the Track date only checkbox checked the ical feed seems to work fine.

Error occurring on demo site:
```
{"error_message":"Eluceo\\iCal\\Domain\\ValueObject\\PointInTime::__construct(): Argument #1 ($dateTime) must be of type ?DateTimeInterface, bool given, called in \/var\/www\/demo.grocy.info\/controllers\/CalendarApiController.php on line 33","error_details":{"stack_trace":"
#0 \/var\/www\/demo.grocy.info\/controllers\/CalendarApiController.php(33): Eluceo\\iCal\\Domain\\ValueObject\\PointInTime->__construct()\n
#1 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/Handlers\/Strategies\/RequestResponse.php(43): Grocy\\Controllers\\CalendarApiController->Ical()\n
#2 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/Routing\/Route.php(384): Slim\\Handlers\\Strategies\\RequestResponse->__invoke()\n
#3 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(81): Slim\\Routing\\Route->handle()\n
#4 \/var\/www\/demo.grocy.info\/middleware\/JsonMiddleware.php(13): Slim\\MiddlewareDispatcher->handle()\n
#5 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(209): Grocy\\Middleware\\JsonMiddleware->__invoke()\n
#6 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(81): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n
#7 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/Routing\/Route.php(341): Slim\\MiddlewareDispatcher->handle()\n
#8 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/Routing\/RouteRunner.php(84): Slim\\Routing\\Route->run()\n
#9 \/var\/www\/demo.grocy.info\/middleware\/AuthMiddleware.php(48): Slim\\Routing\\RouteRunner->handle()\n
#10 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(313): Grocy\\Middleware\\AuthMiddleware->__invoke()\n
#11 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/Middleware\/RoutingMiddleware.php(59): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n
#12 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(147): Slim\\Middleware\\RoutingMiddleware->process()\n
#13 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/Middleware\/ErrorMiddleware.php(107): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n
#14 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(147): Slim\\Middleware\\ErrorMiddleware->process()\n
#15 \/var\/www\/demo.grocy.info\/middleware\/CorsMiddleware.php(30): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n
#16 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(313): Grocy\\Middleware\\CorsMiddleware->__invoke()\n
#17 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(81): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n
#18 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/App.php(215): Slim\\MiddlewareDispatcher->handle()\n
#19 \/var\/www\/demo.grocy.info\/vendor\/slim\/slim\/Slim\/App.php(199): Slim\\App->handle()\n
#20 \/var\/www\/demo.grocy.info\/app.php(106): Slim\\App->run()\n
#21 \/var\/www\/demo.grocy.info\/public\/index.php(45): require_once('...')\n
#22 {main}","file":"\/var\/www\/demo.grocy.info\/vendor\/eluceo\/ical\/src\/Domain\/ValueObject\/PointInTime.php","line":26}}
```

**Comment by berrnd** [comment]
If you want to have this now, replace the file `controllers/CalendarApiController.php` with [that one](https://raw.githubusercontent.com/grocy/grocy/8225215e393d7e977c50c5ae98caeb0429832820/controllers/CalendarApiController.php).
