### ISSUE TITLE
Bug: SQLSTATE[HY000]: General error: 1 no such table: meal_plan_internal_recipe_relation

### ISSUE THREAD

**Issue by MihailMecetin** [grocy/grocy#1548]
After upgrading from 3.0.1 to v.3.1.0 with the update.sh script and opening meal plan, I get this error:

![image](https://user-images.githubusercontent.com/6560286/126895897-2e80c30f-28a1-4cbc-a1a0-bc69ec4a0807.png)

Full Error message:
Error source:
```
/var/www/html/vendor/morris/lessql/src/LessQL/Database.php:108
```

Error message:
```
SQLSTATE[HY000]: General error: 1 no such table: meal_plan_internal_recipe_relation
```

Stack trace:
```
#0 /var/www/html/vendor/morris/lessql/src/LessQL/Database.php(108): PDO->prepare()
#1 /var/www/html/vendor/morris/lessql/src/LessQL/Database.php(491): LessQL\Database->prepare()
#2 /var/www/html/vendor/morris/lessql/src/LessQL/Result.php(149): LessQL\Database->select()
#3 /var/www/html/vendor/morris/lessql/src/LessQL/Result.php(334): LessQL\Result->execute()
#4 /var/www/html/controllers/RecipesController.php(58): LessQL\Result->fetchAll()
#5 /var/www/html/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\Controllers\RecipesController->MealPlan()
#6 /var/www/html/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
#7 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#8 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
#9 /var/www/html/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#10 /var/www/html/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#11 /var/www/html/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#12 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\LocaleMiddleware->__invoke()
#13 /var/www/html/middleware/AuthMiddleware.php(76): class@anonymous->handle()
#14 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\AuthMiddleware->__invoke()
#15 /var/www/html/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): class@anonymous->handle()
#16 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#17 /var/www/html/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle()
#18 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#19 /var/www/html/middleware/CorsMiddleware.php(30): class@anonymous->handle()
#20 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\CorsMiddleware->__invoke()
#21 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle()
#22 /var/www/html/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#23 /var/www/html/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#24 /var/www/html/app.php(106): Slim\App->run()
#25 /var/www/html/public/index.php(45): require_once('/var/www/html/a...')
#26 {main}
```

**Comment by berrnd** [comment]
This is the issue tracker, so for reproducible bugs (like [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests) and on the issue template).

Database migrations run on the root route (so the main page, click the grocy logo), this particular database object was created in [migration 141](https://github.com/grocy/grocy/blob/7ee15946c765f77e1c874b1b5ccf9feb4e079aa1/migrations/0141.sql).

Also [noted in README](https://github.com/grocy/grocy#database-migrations), also already answered (the last time, in general multiple times after each release) [here](https://www.reddit.com/r/grocy/comments/op6p2j).

So, have you opened the main route once after the update? I guess not.
