### ISSUE TITLE
Bug: when I try to add new product

### ISSUE THREAD

**Issue by riggs498** [grocy/grocy#1583]
Error source:
```
/data/grocy/viewcache/766c7e1d7d15840c9c5921d333b789b404d373d8.php:1
```

Error message:
```
count(): Argument #1 ($var) must be of type Countable|array, null given (View: /var/www/grocy/views/components/userfields_thead.blade.php) (View: /var/www/grocy/views/components/userfields_thead.blade.php)
```

Stack trace:
```
#0 /var/www/grocy/vendor/illuminate/view/Engines/PhpEngine.php(60): Illuminate\View\Engines\CompilerEngine->handleViewException()
#1 /var/www/grocy/vendor/illuminate/view/Engines/CompilerEngine.php(61): Illuminate\View\Engines\PhpEngine->evaluatePath()
#2 /var/www/grocy/vendor/illuminate/view/View.php(139): Illuminate\View\Engines\CompilerEngine->get()
#3 /var/www/grocy/vendor/illuminate/view/View.php(122): Illuminate\View\View->getContents()
#4 /var/www/grocy/vendor/illuminate/view/View.php(91): Illuminate\View\View->renderContents()
#5 /var/www/grocy/vendor/berrnd/slim-blade-view/src/Blade.php(173): Illuminate\View\View->render()
#6 /var/www/grocy/vendor/berrnd/slim-blade-view/src/Blade.php(65): Slim\Views\Blade->fetch()
#7 /var/www/grocy/controllers/BaseController.php(179): Slim\Views\Blade->render()
#8 /var/www/grocy/controllers/BaseController.php(202): Grocy\Controllers\BaseController->render()
#9 /var/www/grocy/controllers/StockController.php(168): Grocy\Controllers\BaseController->renderPage()
#10 /var/www/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\Controllers\StockController->ProductEditForm()
#11 /var/www/grocy/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
#12 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#13 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
#14 /var/www/grocy/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#15 /var/www/grocy/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#16 /var/www/grocy/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#17 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\LocaleMiddleware->__invoke()
#18 /var/www/grocy/middleware/AuthMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\AuthMiddleware->__invoke()
#20 /var/www/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#22 /var/www/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#23 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#24 /var/www/grocy/middleware/CorsMiddleware.php(30): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#25 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\CorsMiddleware->__invoke()
#26 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#27 /var/www/grocy/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#28 /var/www/grocy/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#29 /var/www/grocy/app.php(106): Slim\App->run()
#30 /var/www/grocy/public/index.php(45): require_once('...')
#31 {main}
```

**Comment by berrnd** [comment]
(Maybe) The same as #1417.

The issue template mentions to provide the exact steps to reproduce the problem, can be easily done using (private) demo instances. So if you can provide a reproducible way I'm happy to help, otherwise such reports are, sorry, useless.
