### ISSUE TITLE
Bug: Using international characters breaks API querying

### ISSUE THREAD

**Issue by matejdro** [grocy/grocy#1591]
Performing following query:

```
https://my.grocy.instance/api/objects/recipes?query[]=name~Š
```

Will result in a

```
{
    "error_message": "Invalid query",
    "error_details": {
        "stack_trace": "#0 /app/grocy/controllers/BaseApiController.php(50): Grocy\\Controllers\\BaseApiController->filter()\n#1 /app/grocy/controllers/GenericEntityApiController.php(152): Grocy\\Controllers\\BaseApiController->queryData()\n#2 /app/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\\Controllers\\GenericEntityApiController->GetObjects()\n#3 /app/grocy/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\\Handlers\\Strategies\\RequestResponse->__invoke()\n#4 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\\Routing\\Route->handle()\n#5 /app/grocy/middleware/JsonMiddleware.php(13): Slim\\MiddlewareDispatcher->handle()\n#6 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): Grocy\\Middleware\\JsonMiddleware->__invoke()\n#7 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle()\n#8 /app/grocy/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\\MiddlewareDispatcher->handle()\n#9 /app/grocy/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\\Routing\\Route->run()\n#10 /app/grocy/middleware/LocaleMiddleware.php(16): Slim\\Routing\\RouteRunner->handle()\n#11 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\\Middleware\\LocaleMiddleware->__invoke()\n#12 /app/grocy/middleware/AuthMiddleware.php(76): class@anonymous->handle()\n#13 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\\Middleware\\AuthMiddleware->__invoke()\n#14 /app/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): class@anonymous->handle()\n#15 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\\Middleware\\RoutingMiddleware->process()\n#16 /app/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle()\n#17 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\\Middleware\\ErrorMiddleware->process()\n#18 /app/grocy/middleware/CorsMiddleware.php(30): class@anonymous->handle()\n#19 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\\Middleware\\CorsMiddleware->__invoke()\n#20 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle()\n#21 /app/grocy/vendor/slim/slim/Slim/App.php(215): Slim\\MiddlewareDispatcher->handle()\n#22 /app/grocy/vendor/slim/slim/Slim/App.php(199): Slim\\App->handle()\n#23 /app/grocy/app.php(106): Slim\\App->run()\n#24 /app/grocy/public/index.php(45): require_once('/app/grocy/app....')\n#25 {main}",
        "file": "/app/grocy/controllers/BaseApiController.php",
        "line": 95
    }
}
```

With grocy 3.1.0

**Comment by berrnd** [comment]
Was recently also a problem with cyrillic characters (#1296).

The query value are filtered via this regular expression:
https://github.com/grocy/grocy/blob/22db124624ea68b9d128fff854f31c50343d4fec/controllers/BaseApiController.php#L13

If you maybe have any idea what the best way / regex is to allow any character, while only allowing specific special characters (`$`, `#`, `-` and so on), would be much appreciated.

**Comment by matejdro** [comment]
This has worked well for me in the past: https://stackoverflow.com/a/6005511/5273071

**Comment by matejdro** [comment]
Can confirm that the last released version fixes this. Thanks!
