### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by JackAlbertHarker** [grocy/grocy#1597]
After auto update, Grocy is unusable in HASSio/Rasp4
Chores in Lovelace Cards, still appear to work.
Suspect some barcode related problem.

Please advise fix procedure inlcuding path to relevant files in HASSIO, how to get there. unable to find var/.... in file editor.

Copy of error log
Error source:
```
/var/www/grocy/services/DatabaseService.php:35
```

Error message:
```
SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: product_barcodes.barcode
```

Stack trace:
```
#0 /var/www/grocy/services/DatabaseService.php(35): PDO->exec()
#1 /var/www/grocy/services/DatabaseMigrationService.php(63): Grocy\Services\DatabaseService->ExecuteDbStatement()
#2 /var/www/grocy/services/DatabaseMigrationService.php(33): Grocy\Services\DatabaseMigrationService->ExecuteSqlMigrationWhenNeeded()
#3 /var/www/grocy/controllers/SystemController.php(27): Grocy\Services\DatabaseMigrationService->MigrateDatabase()
#4 /var/www/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\Controllers\SystemController->Root()
#5 /var/www/grocy/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
#6 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#7 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
#8 /var/www/grocy/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#9 /var/www/grocy/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#10 /var/www/grocy/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#11 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\LocaleMiddleware->__invoke()
#12 /var/www/grocy/middleware/AuthMiddleware.php(31): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#13 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\AuthMiddleware->__invoke()
#14 /var/www/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#15 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#16 /var/www/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#17 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#18 /var/www/grocy/middleware/CorsMiddleware.php(30): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\CorsMiddleware->__invoke()
#20 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /var/www/grocy/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#22 /var/www/grocy/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#23 /var/www/grocy/app.php(106): Slim\App->run()
#24 /var/www/grocy/public/index.php(45): require_once('...')
#25 {main}
```

**Comment by berrnd** [comment]
This is not the repo of the Home Assistant Add-on (=> [hassio-addons/addon-grocy](https://github.com/hassio-addons/addon-grocy), personally have absolutely no clue about HASS since I don't use that, so cannot really help for specifically that) and this is obviously a known and already in v3.1.1 fixed problem (references #1546, of course also mentioned in the [changelog](https://grocy.info/changelog)).

However, the Home Assistant Add-on is still on v3.1.0, [as far is I can see](https://github.com/hassio-addons/addon-grocy/releases).

So this is not a bug and you have successfully ignored what's [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests) and on the issue template about bug/help requests, used the wrong place and obviously pretty much also haven't even searched a tiny bit about that before opening this issue, what should I say...

You don't even have to wait until the Home Assistant Add-on updates to the recent grocy release or have to change/replaces any files manually, you can also resolve this manually by checking the affected products/barcodes, all that is explained in https://github.com/grocy/grocy/issues/1546#issuecomment-885688570.
