### ISSUE TITLE
Bug: Shoppinglist stopped working, gives an error now

### ISSUE THREAD

**Issue by thesatman** [grocy/grocy#1629]
Error source:
```
/app/grocy/services/LocalizationService.php:76
```

Error message:
```
abs(): Argument #1 ($num) must be of type int|float, string given (View: /app/grocy/views/shoppinglist.blade.php)
```

Stack trace:
```
#0 /app/grocy/vendor/illuminate/view/Engines/PhpEngine.php(60): Illuminate\View\Engines\CompilerEngine->handleViewException()
#1 /app/grocy/vendor/illuminate/view/Engines/CompilerEngine.php(61): Illuminate\View\Engines\PhpEngine->evaluatePath()
#2 /app/grocy/vendor/illuminate/view/View.php(139): Illuminate\View\Engines\CompilerEngine->get()
#3 /app/grocy/vendor/illuminate/view/View.php(122): Illuminate\View\View->getContents()
#4 /app/grocy/vendor/illuminate/view/View.php(91): Illuminate\View\View->renderContents()
#5 /app/grocy/vendor/berrnd/slim-blade-view/src/Blade.php(173): Illuminate\View\View->render()
#6 /app/grocy/vendor/berrnd/slim-blade-view/src/Blade.php(65): Slim\Views\Blade->fetch()
#7 /app/grocy/controllers/BaseController.php(179): Slim\Views\Blade->render()
#8 /app/grocy/controllers/BaseController.php(202): Grocy\Controllers\BaseController->render()
#9 /app/grocy/controllers/StockController.php(368): Grocy\Controllers\BaseController->renderPage()
#10 /app/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\Controllers\StockController->ShoppingList()
#11 /app/grocy/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
#12 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#13 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
#14 /app/grocy/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#15 /app/grocy/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#16 /app/grocy/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#17 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\LocaleMiddleware->__invoke()
#18 /app/grocy/middleware/AuthMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\AuthMiddleware->__invoke()
#20 /app/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#22 /app/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#23 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#24 /app/grocy/middleware/CorsMiddleware.php(30): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#25 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\CorsMiddleware->__invoke()
#26 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#27 /app/grocy/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#28 /app/grocy/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#29 /app/grocy/app.php(106): Slim\App->run()
#30 /app/grocy/public/index.php(45): require_once('...')
#31 {main}
```

System info:
```
{
    "grocy_version": {
        "Version": "3.1.2",
        "ReleaseDate": "2021-09-27"
    },
    "php_version": "8.0.10",
    "sqlite_version": "3.35.5",
    "os": "Linux 4.15.0-154-generic #161-Ubuntu SMP Fri Jul 30 13:04:17 UTC 2021 x86_64",
    "client": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/93.0.4577.82 Safari\/537.36"
}
```

**Comment by berrnd** [comment]
Not reproducible [on the demo instance ](https://demo.grocy.info/shoppinglist)- can't help unless we have it reproducible...

Potentially just a translation problem, which localization are you using?

**Comment by thesatman** [comment]
I know, I tested the demo.   
  

  
I normally use Norwegian, but I get the same result when I switch to English.   
  

  

  

  
  
  
  
>

**Comment by thesatman** [comment]
It worked fine until the update automatically got installed. I delayed the update on purpose because it is not compatible with the Android app.   
  

  
Can I revert to the previous version? Just to test if the error disappears?   
  

  

  

  
  
  
  
  
>

**Comment by berrnd** [comment]
Still needs a reproducible way to solve it, does not happen on the demo instance, does not happen on my private instance...

> Can I revert to the previous version?

I would always create a backup before updating, then simply restoring that - [`update.sh`](https://raw.githubusercontent.com/grocy/grocy/master/update.sh) ([README ref](https://github.com/grocy/grocy#how-to-update)) creates backups automatically at `/data/backups`.

**Comment by berrnd** [comment]
Best guess based on the error message is the patch done in https://github.com/grocy/grocy/commit/282168f92ca2980f70e3248d789c3d08f3a4e5ea.

Replace the file `services/LocalizationService.php` with [that one](https://raw.githubusercontent.com/grocy/grocy/282168f92ca2980f70e3248d789c3d08f3a4e5ea/services/LocalizationService.php) if you want to have/test this now.

**Comment by MKBontwikkeling** [comment]
Hi guys,

I'm getting this error too. I tried to scan for a product with an Android scanner app to send to a Windows PC which had the Grocy frontend opened. I got the error message below. Problem is I can't reset it. I tried to set the language from dutch to english but this was also unsuccesful.

Any ideas? I just installed Grocy so it's kind of a bummer that I can't use it now.


Error source:
```
`/config/data/viewcache/ecd1e6f5a21d55ab53037d49dc3b6ad6.php:285
````

Error message:
```
`ceil(): Argument #1 ($num) must be of type int|float, string given (View: /app/www/views/shoppinglist.blade.php)
````

Stack trace:
```
#0 /app/www/packages/illuminate/view/Engines/PhpEngine.php(60): Illuminate\View\Engines\CompilerEngine->handleViewException()
#1 /app/www/packages/illuminate/view/Engines/CompilerEngine.php(75): Illuminate\View\Engines\PhpEngine->evaluatePath()
#2 /app/www/packages/illuminate/view/View.php(209): Illuminate\View\Engines\CompilerEngine->get()
#3 /app/www/packages/illuminate/view/View.php(192): Illuminate\View\View->getContents()
#4 /app/www/packages/illuminate/view/View.php(161): Illuminate\View\View->renderContents()
#5 /app/www/packages/berrnd/slim-blade-view/src/Blade.php(173): Illuminate\View\View->render()
#6 /app/www/packages/berrnd/slim-blade-view/src/Blade.php(65): Slim\Views\Blade->fetch()
#7 /app/www/controllers/BaseController.php(186): Slim\Views\Blade->render()
#8 /app/www/controllers/BaseController.php(209): Grocy\Controllers\BaseController->render()
#9 /app/www/controllers/StockController.php(421): Grocy\Controllers\BaseController->renderPage()
#10 /app/www/packages/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): Grocy\Controllers\StockController->ShoppingList()
#11 /app/www/packages/slim/slim/Slim/Routing/Route.php(363): Slim\Handlers\Strategies\RequestResponse->__invoke()
#12 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(73): Slim\Routing\Route->handle()
#13 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(73): Slim\MiddlewareDispatcher->handle()
#14 /app/www/packages/slim/slim/Slim/Routing/Route.php(321): Slim\MiddlewareDispatcher->handle()
#15 /app/www/packages/slim/slim/Slim/Routing/RouteRunner.php(74): Slim\Routing\Route->run()
#16 /app/www/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#17 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(280): Grocy\Middleware\LocaleMiddleware->__invoke()
#18 /app/www/middleware/AuthMiddleware.php(77): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(280): Grocy\Middleware\AuthMiddleware->__invoke()
#20 /app/www/packages/slim/slim/Slim/Middleware/RoutingMiddleware.php(45): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(129): Slim\Middleware\RoutingMiddleware->process()
#22 /app/www/packages/slim/slim/Slim/Middleware/ErrorMiddleware.php(77): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#23 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(129): Slim\Middleware\ErrorMiddleware->process()
#24 /app/www/middleware/CorsMiddleware.php(27): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#25 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(280): Grocy\Middleware\CorsMiddleware->__invoke()
#26 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(73): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#27 /app/www/packages/slim/slim/Slim/App.php(209): Slim\MiddlewareDispatcher->handle()
#28 /app/www/packages/slim/slim/Slim/App.php(193): Slim\App->handle()
#29 /app/www/app.php(133): Slim\App->run()
#30 /app/www/public/index.php(45): require_once('...')
#31 {main}
```

System info:
```
{
    "grocy_version": {
        "Version": "4.4.0",
        "ReleaseDate": "2025-01-24"
    },
    "php_version": "8.3.15",
    "sqlite_version": "3.45.3",
    "os": "Linux 4.4.302+ #72806 SMP Thu Sep 5 13:41:01 CST 2024 x86_64",
    "client": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/132.0.0.0 Safari\/537.36"
}
```

**Comment by berrnd** [comment]
> `ceil(): Argument #1 ($num) must be of type int|float, string given (View: /app/www/views/shoppinglist.blade.php)

You pretty clearly managed to enter a non-number where a number is expected. I would say that isn't possible via Grocy's web frontend. Provide a 100 % reproducible example otherwise and I maybe use some of my time to look into it.

Also related to #2641 and all the other referenced duplicates there and unrelated to this year old thread - please don't spam random threads with off-topic stuff.

&nbsp;
> I just installed Grocy so it's kind of a bummer that I can't use it now.

You picked a random free Open Source hobby project of a random guy from the internet - don't have any expectations - I'm (and nobody else) is even not obligated to help over fix anything, if there is really a problem. So I don't really get what this argument should help with at all.

**Comment by MKBontwikkeling** [comment]
Sorry, I'm unaware of any Github etiquettes unfortunatly. I love the idea of Grocy and was happy to install it. It was merely my excitement for the project that made me state "too bad I can't use it yet". Installing a random project from a random guy is certainly not the case, as I've been following Grocy for years. I'm a fan. Was only just now able to get it installed for the first time. I appologize if I offended anyone, because I appreciate all the work that went into Grocy (and oss in general). Nobody is obligated to help me for sure. Probably offtopic too, sorry didn't know where else to reply.
