### ISSUE TITLE
Bug: no such table: users on first launch

### ISSUE THREAD

**Issue by xyttyxy** [grocy/grocy#1671]
On a fresh install on CentOS7, PHP 7.3, I was able to view the demo database. Updating the demo db also works. 
But once I switch to production, past the login page with admin/admin for username and pw I get the following error: 

Error source:
```
/var/www/html/grocy/vendor/morris/lessql/src/LessQL/Database.php:108
```

Error message:
```
SQLSTATE[HY000]: General error: 1 no such table: users
```

Stack trace:
```
#0 /var/www/html/grocy/vendor/morris/lessql/src/LessQL/Database.php(108): PDO->prepare('SELECT * FROM `...')
#1 /var/www/html/grocy/vendor/morris/lessql/src/LessQL/Database.php(491): LessQL\Database->prepare('SELECT * FROM `...')
#2 /var/www/html/grocy/vendor/morris/lessql/src/LessQL/Result.php(149): LessQL\Database->select('users', Array)
#3 /var/www/html/grocy/vendor/morris/lessql/src/LessQL/Result.php(322): LessQL\Result->execute()
#4 /var/www/html/grocy/middleware/DefaultAuthMiddleware.php(34): LessQL\Result->fetch()
#5 /var/www/html/grocy/controllers/LoginController.php(23): Grocy\Middleware\DefaultAuthMiddleware::ProcessLogin(Array)
#6 /var/www/html/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\Controllers\LoginController->ProcessLogin(Object(Slim\Http\ServerRequest), Object(Slim\Http\Response), Array)
#7 /var/www/html/grocy/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\ServerRequest), Object(Slim\Http\Response), Array)
#8 /var/www/html/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle(Object(Slim\Http\ServerRequest))
#9 /var/www/html/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#10 /var/www/html/grocy/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#11 /var/www/html/grocy/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run(Object(Slim\Http\ServerRequest))
#12 /var/www/html/grocy/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle(Object(Slim\Http\ServerRequest))
#13 /var/www/html/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\LocaleMiddleware->__invoke(Object(Slim\Http\ServerRequest), Object(Slim\Routing\RouteRunner))
#14 /var/www/html/grocy/middleware/AuthMiddleware.php(36): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#15 /var/www/html/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\AuthMiddleware->__invoke(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#16 /var/www/html/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#17 /var/www/html/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#18 /var/www/html/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#19 /var/www/html/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#20 /var/www/html/grocy/middleware/CorsMiddleware.php(30): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#21 /var/www/html/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\CorsMiddleware->__invoke(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#22 /var/www/html/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#23 /var/www/html/grocy/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#24 /var/www/html/grocy/vendor/slim/slim/Slim/App.php(199): Slim\App->handle(Object(Slim\Http\ServerRequest))
#25 /var/www/html/grocy/app.php(106): Slim\App->run()
#26 /var/www/html/grocy/public/index.php(45): require_once('/var/www/html/g...')
#27 {main}
```

System info:
```
{
    "grocy_version": {
        "Version": "3.1.2",
        "ReleaseDate": "2021-09-27"
    },
    "php_version": "7.3.32",
    "sqlite_version": "3.36.0",
    "os": "Linux 5.8.10-1.el7.elrepo.x86_64 #1 SMP Thu Sep 17 10:40:48 EDT 2020 x86_64",
    "client": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/95.0.4638.54 Safari\/537.36 Edg\/95.0.1020.40"
}
```

Perhaps relevant is that I compiled sqlite3 myself (both the binary under /usr/bin and the shared object under /usr/lib64), as my distribution provides only up to sqlite 3.7.17. 

edit: 
On my data directory an empty grocy.db (0 bytes) file is created.

**Comment by xyttyxy** [comment]
I went through other issues and found advices on removing data/grocy.db and pointing the browser to grocy root location. In my case it was https://<domain-name>/grocy/public/. Now the database gets created normally. 

closing this.

**Comment by berrnd** [comment]
Also definetly not a reproducible bug, more a help request - this should go to the [subreddit](https://www.reddit.com/r/grocy) as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests) and on the issue template.
