### ISSUE TITLE
Bug: Error in new Recip

### ISSUE THREAD

**Issue by AndreasSteibl** [grocy/grocy#1691]
Hi i just wanted to add a new recip, now i get en error every time i would like to open the recip.

`Error source:
```
/config/data/viewcache/80b12845534a6a50d9ab41bd668060c18bfd40ac.php:191
```

Error message:
```
round(): Argument #1 ($num) must be of type int|float, string given (View: /app/grocy/views/recipeform.blade.php)
```

Stack trace:
```
#0 /app/grocy/vendor/illuminate/view/Engines/PhpEngine.php(60): Illuminate\View\Engines\CompilerEngine->handleViewException()
#1 /app/grocy/vendor/illuminate/view/Engines/CompilerEngine.php(61): Illuminate\View\Engines\PhpEngine->evaluatePath()
#2 /app/grocy/vendor/illuminate/view/View.php(139): Illuminate\View\Engines\CompilerEngine->get()
#3 /app/grocy/vendor/illuminate/view/View.php(122): Illuminate\View\View->getContents()
#4 /app/grocy/vendor/illuminate/view/View.php(91): Illuminate\View\View->renderContents()
#5 /app/grocy/vendor/berrnd/slim-blade-view/src/Blade.php(173): Illuminate\View\View->render()
#6 /app/grocy/vendor/berrnd/slim-blade-view/src/Blade.php(65): Slim\Views\Blade->fetch()
#7 /app/grocy/controllers/BaseController.php(179): Slim\Views\Blade->render()
#8 /app/grocy/controllers/BaseController.php(202): Grocy\Controllers\BaseController->render()
#9 /app/grocy/controllers/RecipesController.php(161): Grocy\Controllers\BaseController->renderPage()
#10 /app/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\Controllers\RecipesController->RecipeEditForm()
#11 /app/grocy/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
#12 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#13 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
#14 /app/grocy/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#15 /app/grocy/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#16 /app/grocy/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#17 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\LocaleMiddleware->__invoke()
#18 /app/grocy/middleware/AuthMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\AuthMiddleware->__invoke()
#20 /app/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#22 /app/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#23 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#24 /app/grocy/middleware/CorsMiddleware.php(30): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#25 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\CorsMiddleware->__invoke()
#26 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#27 /app/grocy/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#28 /app/grocy/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#29 /app/grocy/app.php(106): Slim\App->run()
#30 /app/grocy/public/index.php(45): require_once('...')
#31 {main}
```

System info:
```
{
    "grocy_version": {
        "Version": "3.1.3",
        "ReleaseDate": "2021-11-14"
    },
    "php_version": "8.0.12",
    "sqlite_version": "3.35.5",
    "os": "Linux 5.10.28-Unraid #1 SMP Wed Apr 7 08:23:18 PDT 2021 x86_64",
    "client": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/96.0.4664.45 Safari\/537.36"
}
````

**Comment by berrnd** [comment]
Would be great if you can provide a reproducible way (also mentioned on the issue template).

The error references [that line](https://github.com/grocy/grocy/blob/8876c6cf95df5030d0fc4d8e1ea6dd9ed0b794e8/views/recipeform.blade.php#L189). It's about rounding of the ingredient amount which obviously somehow isn't a number. Of course this can be safe-checked there, but it's however not possible to produce this via the frontend...

**Comment by AndreasSteibl** [comment]
I don't knwo exactly how i produces the wrong recipe.

I downloaded a sqllite db viewer and viewed teh recip pos table - the amount was NAN - i changed it to 1 and now the recip opens without an error

**Comment by AndreasSteibl** [comment]
Hmmm i get the error again.

I have a product 
Knoblauch - with unit "Stk"

in my recip a i have this procut knoblauch
if i change the position, the amount and the unit is empty - i can edit the amount, but the unit isn't editable and it is empty
if i edit the amount and save the position - i get the error.

If i select a new product (i can select the same product Knoblauch) - it fills the correct unit (Stk)
than i enter the amount and save - it works, but in the overview of the recip i see that the unit is not "Stk" it is "kg"

**Comment by berrnd** [comment]
Then please try to reproduce that on a [persistent demo instance](https://www.reddit.com/r/grocy/comments/jwnk9b) (like also mentioned on the issue template) - can't help without all the missing details (quantity units and conversions involved, the exact product configuration, and all the rest).

**Comment by AndreasSteibl** [comment]
I can't reproduce it in the demo.
After i delete the product and create it new, it works

**Comment by Dahu88** [comment]
Hello we got the same issue today on version 3.1.2
We entered (via the API) the quantity "4 or 5" and then it was impossible to edit the recipe.
We managed to delete the faulty ingredient (with the API), and added it correctly by hand.

**Comment by berrnd** [comment]
> We entered (via the API) the quantity "4 or 5"

No surprise that rounding `4 or 5` fails, roughly guessing that even stock fulfillment checks and the rest will fail too ([GIGO](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out))...
