### ISSUE TITLE
Bug: HA addon, missing file and undefined constant "GROCY_SHOW_AUTH_VIEWS"

### ISSUE THREAD

**Issue by renarena** [grocy/grocy#1726]
I updated the homeassistant addon from v0.14 to v0.16. (could not use v0.15 due to a parent product error in my database) It uses grocy 3.1.3 from 2021-12-09
I am not sure if the error is caused by grocy or by usign it as homeassistant addon.
Is there a need / an abilitiy to clear viewcache?

```2021/12/28 17:15:17 [error] 1731#1731: *7 open() "/var/www/grocy/public/components_unmanaged/noto-sans-v11-latin/noto-sans-v11-latin.min.css" failed (2: No such file or directory), client: 192.168.1.40, server: a0d7b954-grocy, request: "GET /components_unmanaged/noto-sans-v11-latin/noto-sans-v11-latin.min.css?v=3.1.3 HTTP/1.1", host: "192.168.1.222:9192", referrer: "http://192.168.1.222:9192/login"
2021/12/28 17:16:10 [error] 1731#1731: *6 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Undefined constant "GROCY_SHOW_AUTH_VIEWS" in /data/grocy/viewcache/ee91662b47d4b5bfed27ce28d018967d808016cb.php:461
Stack trace:
#0 /var/www/grocy/vendor/illuminate/filesystem/Filesystem.php(107): require()
#1 /var/www/grocy/vendor/illuminate/filesystem/Filesystem.php(108): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()
#2 /var/www/grocy/vendor/illuminate/view/Engines/PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire()
#3 /var/www/grocy/vendor/illuminate/view/Engines/CompilerEngine.php(61): Illuminate\View\Engines\PhpEngine->evaluatePath()
#4 /var/www/grocy/vendor/illuminate/view/View.php(139): Illuminate\View\Engines\CompilerEngine->get()
#5 /var/www/grocy/vendor/illuminate/view/View.php(122): Illuminate\View\View->getContents()
#6 /var/www/grocy/vendor/illuminate/view/View.php(91): Illuminate\View\View->renderContents()
#7 /data/grocy/viewcache/161f4c17296927a7f5dd3c75f477e6987e8ea606.php(49): Illuminate\View\View" while reading response header from upstream, client: 192.168.1.40, server: a0d7b954-grocy, request: "GET /stockoverview HTTP/1.1", upstream: "fastcgi://127.0.0.1:9001", host: "192.168.1.222:9192", referrer: "http://192.168.1.222:9192/login"
2021/12/28 17:23:23 [error] 1731#1731: *13 open() "/var/www/grocy/public/components_unmanaged/noto-sans-v11-latin/noto-sans-v11-latin.min.css" failed (2: No such file or directory), client: 192.168.1.40, server: a0d7b954-grocy, request: "GET /components_unmanaged/noto-sans-v11-latin/noto-sans-v11-latin.min.css HTTP/1.1", host: "192.168.1.222:9192"
```

**Comment by berrnd** [comment]
The constant `GROCY_SHOW_AUTH_VIEWS` is not used anywhere since v3.1.0 ([commit ref](https://github.com/grocy/grocy/commit/47c936e02634a90e7fe5c2c65a330d6acc170a5a), [GitHub code search ref](https://github.com/grocy/grocy/search?q=GROCY_SHOW_AUTH_VIEWS&type=code)), so can only be about an outdated viewcache ([README mentions](https://github.com/grocy/grocy#how-to-update) to clean `data/viewcache` on updates) or mixed up files from different versions or whatever.

I can't help with anything Homeassistant related due to I'm not using that at all anywhere. Beside that, this is the place for reproducible bugs or feature requests (like also [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests)) and not the one for help requests and also the HA Add-on is not maintained here.
