### ISSUE TITLE
Bug: iCal link give TimeZone error

### ISSUE THREAD

**Issue by TurnrDev** [grocy/grocy#1754]
Visiting the generated iCal url gives an error about Epoch doesn't fit in a PHP integer

```
{
  "error_message": "Epoch doesn't fit in a PHP integer",
  "error_details": {
    "stack_trace": "#0 C:\\Users\\Jay\\AppData\\Roaming\\grocy-desktop\\grocy\\vendor\\eluceo\\ical\\src\\Domain\\Entity\\TimeZone.php(46): DateTimeImmutable->getTimestamp()\n#1 C:\\Users\\Jay\\AppData\\Roaming\\grocy-desktop\\grocy\\controllers\\CalendarApiController.php(77): Eluceo\\iCal\\Domain\\Entity\\TimeZone::createFromPhpDateTimeZone()\n#2 C:\\Users\\Jay\\AppData\\Roaming\\grocy-desktop\\grocy\\vendor\\slim\\slim\\Slim\\Handlers\\Strategies\\RequestResponse.php(43): Grocy\\Controllers\\CalendarApiController->Ical()\n#3 C:\\Users\\Jay\\AppData\\Roaming\\grocy-desktop\\grocy\\vendor\\slim\\slim\\Slim\\Routing\\Route.php(384): Slim\\Handlers\\Strategies\\RequestResponse->__invoke()\n#4 C:\\Users\\Jay\\AppData\\Roaming\\grocy-desktop\\grocy\\vendor\\slim\\slim\\Slim\\MiddlewareDispatcher.php(81): Slim\\Routing\\Route->handle()\n#5 C:\\Users\\Jay\\AppData\\Roaming\\grocy-desktop\\grocy\\middleware\\JsonMiddleware.php(13): Slim\\MiddlewareDispatcher->handle()\n#6 C:\\Users\\Jay\\AppData\\Roaming\\grocy-desktop\\grocy\\vendor\\slim\\slim\\Slim\\MiddlewareDispatcher.php(209): Grocy\\Middleware\\JsonMiddleware->__invoke()\n#7 C:\\Users\\Jay\\AppData\\Roaming\\grocy-desktop\\grocy\\vendor\\slim\\slim\\Slim\\MiddlewareDispatcher.php(81): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#8 C:\\Users\\Jay\\AppData\\Roaming\\grocy-desktop\\grocy\\vendor\\slim\\slim\\Slim\\Routing\\Route.php(341): Slim\\MiddlewareDispatcher->handle()\n#9 C:\\Users\\Jay\\AppData\\Roaming\\grocy-desktop\\grocy\\vendor\\slim\\slim\\Slim\\Routing\\RouteRunner.php(84): Slim\\Routing\\Route->run()\n#10 C:\\Users\\Jay\\AppData\\Roaming\\grocy-desktop\\grocy\\middleware\\LocaleMiddleware.php(16): Slim\\Routing\\RouteRunner->handle()\n#11 C:\\Users\\Jay\\AppData\\Roaming\\grocy-desktop\\grocy\\vendor\\slim\\slim\\Slim\\MiddlewareDispatcher.php(313): Grocy\\Middleware\\LocaleMiddleware->__invoke()\n#12 C:\\Users\\Jay\\AppData\\Roaming\\grocy-desktop\\grocy\\middleware\\AuthMiddleware.php(48): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#13 C:\\Users\\Jay\\AppData\\Roaming\\grocy-desktop\\grocy\\vendor\\slim\\slim\\Slim\\MiddlewareDispatcher.php(313): Grocy\\Middleware\\AuthMiddleware->__invoke()\n#14 C:\\Users\\Jay\\AppData\\Roaming\\grocy-desktop\\grocy\\vendor\\slim\\slim\\Slim\\Middleware\\RoutingMiddleware.php(59): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#15 C:\\Users\\Jay\\AppData\\Roaming\\grocy-desktop\\grocy\\vendor\\slim\\slim\\Slim\\MiddlewareDispatcher.php(147): Slim\\Middleware\\RoutingMiddleware->process()\n#16 C:\\Users\\Jay\\AppData\\Roaming\\grocy-desktop\\grocy\\vendor\\slim\\slim\\Slim\\Middleware\\ErrorMiddleware.php(107): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#17 C:\\Users\\Jay\\AppData\\Roaming\\grocy-desktop\\grocy\\vendor\\slim\\slim\\Slim\\MiddlewareDispatcher.php(147): Slim\\Middleware\\ErrorMiddleware->process()\n#18 C:\\Users\\Jay\\AppData\\Roaming\\grocy-desktop\\grocy\\middleware\\CorsMiddleware.php(30): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#19 C:\\Users\\Jay\\AppData\\Roaming\\grocy-desktop\\grocy\\vendor\\slim\\slim\\Slim\\MiddlewareDispatcher.php(313): Grocy\\Middleware\\CorsMiddleware->__invoke()\n#20 C:\\Users\\Jay\\AppData\\Roaming\\grocy-desktop\\grocy\\vendor\\slim\\slim\\Slim\\MiddlewareDispatcher.php(81): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#21 C:\\Users\\Jay\\AppData\\Roaming\\grocy-desktop\\grocy\\vendor\\slim\\slim\\Slim\\App.php(215): Slim\\MiddlewareDispatcher->handle()\n#22 C:\\Users\\Jay\\AppData\\Roaming\\grocy-desktop\\grocy\\vendor\\slim\\slim\\Slim\\App.php(199): Slim\\App->handle()\n#23 C:\\Users\\Jay\\AppData\\Roaming\\grocy-desktop\\grocy\\app.php(106): Slim\\App->run()\n#24 C:\\Users\\Jay\\AppData\\Roaming\\grocy-desktop\\grocy\\public\\index.php(45): require_once('...')\n#25 {main}",
    "file": "C:\\Users\\Jay\\AppData\\Roaming\\grocy-desktop\\grocy\\vendor\\eluceo\\ical\\src\\Domain\\Entity\\TimeZone.php",
    "line": 46
  }
}
```

I'm using the Windows .exe version grocy-desktop 1.11.0.0 and grocy 3.1.3
```
Version 3.1.3
Released on 2021-11-14 2 months ago

PHP Version 8.0.8
SQLite Version 3.33.0
OS Windows NT 10.0 build 19044 (Windows 10) i586
Client Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
```

**Comment by berrnd** [comment]
Please provide for future requests a reprodcuible example on a [persistent demo instance](https://www.reddit.com/r/grocy/comments/jwnk9b), as also mentioned on the issue template.

However, I looked into this and this is not a grocy issues, so the wrong place here.

grocy-desktop is a x86 application (to fit any device), therefore bundles a x86 PHP runtime - this error message clearly leads to that this is a 32-bit problem.

Moving this to [grocy/grocy-desktop](https://github.com/grocy/grocy-desktop), the only solution would be to drop x86 support, don't know if that's the best thing. I would recommend to use a "real webserver", especially when you want to use externally shared things like the iCal integration.
