### ISSUE TITLE
Bug: Stock journal - SQL error: no such column: product_id 

### ISSUE THREAD

**Issue by metronidazole** [grocy/grocy#1766]
I've had a grocy install for a couple years now. I tried going to the stock journal for the first time and had the following error. Grocy version is listed below:

Error source:
```
/app/grocy/vendor/morris/lessql/src/LessQL/Database.php:108
```

Error message:
```
SQLSTATE[HY000]: General error: 1 no such column: product_id (View: /app/grocy/views/stockjournal.blade.php)
```

Stack trace:
```
#0 /app/grocy/vendor/illuminate/view/Engines/PhpEngine.php(60): Illuminate\View\Engines\CompilerEngine->handleViewException()
#1 /app/grocy/vendor/illuminate/view/Engines/CompilerEngine.php(61): Illuminate\View\Engines\PhpEngine->evaluatePath()
#2 /app/grocy/vendor/illuminate/view/View.php(139): Illuminate\View\Engines\CompilerEngine->get()
#3 /app/grocy/vendor/illuminate/view/View.php(122): Illuminate\View\View->getContents()
#4 /app/grocy/vendor/illuminate/view/View.php(91): Illuminate\View\View->renderContents()
#5 /app/grocy/vendor/berrnd/slim-blade-view/src/Blade.php(173): Illuminate\View\View->render()
#6 /app/grocy/vendor/berrnd/slim-blade-view/src/Blade.php(65): Slim\Views\Blade->fetch()
#7 /app/grocy/controllers/BaseController.php(179): Slim\Views\Blade->render()
#8 /app/grocy/controllers/BaseController.php(202): Grocy\Controllers\BaseController->render()
#9 /app/grocy/controllers/StockController.php(62): Grocy\Controllers\BaseController->renderPage()
#10 /app/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\Controllers\StockController->Journal()
#11 /app/grocy/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
#12 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#13 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
#14 /app/grocy/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#15 /app/grocy/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#16 /app/grocy/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#17 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\LocaleMiddleware->__invoke()
#18 /app/grocy/middleware/AuthMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\AuthMiddleware->__invoke()
#20 /app/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#22 /app/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#23 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#24 /app/grocy/middleware/CorsMiddleware.php(30): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#25 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\CorsMiddleware->__invoke()
#26 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#27 /app/grocy/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#28 /app/grocy/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#29 /app/grocy/app.php(106): Slim\App->run()
#30 /app/grocy/public/index.php(45): require_once('...')
#31 {main}
```

System info:
```
{
    "grocy_version": {
        "Version": "3.1.3",
        "ReleaseDate": "2021-11-14"
    },
    "php_version": "8.0.13",
    "sqlite_version": "3.35.5",
    "os": "Linux 5.10.28-Unraid #1 SMP Wed Apr 7 08:23:18 PDT 2021 x86_64",
    "client": "Mozilla\/5.0 (X11; Linux x86_64; rv:96.0) Gecko\/20100101 Firefox\/96.0"
}
```

**Comment by metronidazole** [comment]
I moved my install to another container and that seemed to resolve the problem.

**Comment by berrnd** [comment]
Database migrations are executed on the root route as [mentioned in README](https://github.com/grocy/grocy#database-migrations). So updating and directly accessing any non-root route page most likely will cause errors, but that's not a surprise.
