### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by undergroundoyo** [grocy/grocy#1852]
Error source:
```
/app/grocy/vendor/morris/lessql/src/LessQL/Database.php:108
```

Error message:
```
SQLSTATE[HY000]: General error: 1 no such column: no_own_stock (View: /app/grocy/views/components/productpicker.blade.php) (View: /app/grocy/views/components/productpicker.blade.php)
```

Stack trace:
```
#0 /app/grocy/vendor/illuminate/view/Engines/PhpEngine.php(60): Illuminate\View\Engines\CompilerEngine->handleViewException()
#1 /app/grocy/vendor/illuminate/view/Engines/CompilerEngine.php(61): Illuminate\View\Engines\PhpEngine->evaluatePath()
#2 /app/grocy/vendor/illuminate/view/View.php(139): Illuminate\View\Engines\CompilerEngine->get()
#3 /app/grocy/vendor/illuminate/view/View.php(122): Illuminate\View\View->getContents()
#4 /app/grocy/vendor/illuminate/view/View.php(91): Illuminate\View\View->renderContents()
#5 /app/grocy/vendor/berrnd/slim-blade-view/src/Blade.php(173): Illuminate\View\View->render()
#6 /app/grocy/vendor/berrnd/slim-blade-view/src/Blade.php(65): Slim\Views\Blade->fetch()
#7 /app/grocy/controllers/BaseController.php(180): Slim\Views\Blade->render()
#8 /app/grocy/controllers/BaseController.php(203): Grocy\Controllers\BaseController->render()
#9 /app/grocy/controllers/StockController.php(33): Grocy\Controllers\BaseController->renderPage()
#10 /app/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\Controllers\StockController->Inventory()
#11 /app/grocy/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
#12 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#13 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
#14 /app/grocy/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#15 /app/grocy/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#16 /app/grocy/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#17 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\LocaleMiddleware->__invoke()
#18 /app/grocy/middleware/AuthMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\AuthMiddleware->__invoke()
#20 /app/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#22 /app/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#23 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#24 /app/grocy/middleware/CorsMiddleware.php(30): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#25 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\CorsMiddleware->__invoke()
#26 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#27 /app/grocy/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#28 /app/grocy/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#29 /app/grocy/app.php(106): Slim\App->run()
#30 /app/grocy/public/index.php(45): require_once('...')
#31 {main}
```

System info:
```
{
    "grocy_version": {
        "Version": "3.3.0",
        "ReleaseDate": "2022-04-08"
    },
    "php_version": "8.0.13",
    "sqlite_version": "3.35.5",
    "os": "Linux 5.10.63-v7+ #1459 SMP Wed Oct 6 16:41:10 BST 2021 armv7l",
    "client": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/100.0.4896.75 Safari\/537.36"
}
```

**Comment by berrnd** [comment]
You upgraded from a previous version and haven't applied database migrations. This is automatically done when visiting the root route - [README excerpt](https://github.com/grocy/grocy#database-migrations): 

> Database schema migration is automatically done when visiting the root (`/`) route (click on the logo in the left upper edge).

So simply do that and this "bug" will be resolved.

Exactly that has been mentioned there just a couple of hours ago: https://www.reddit.com/r/grocy/comments/tzq8cm
