### ISSUE TITLE
Bug: SQLSTATE[HY000]: General error: 1 near "OVER": syntax error

### ISSUE THREAD

**Issue by roland-d** [grocy/grocy#1857]
Hello,

Today I decided to update my Grocy installation from version 3.1.3 to 3.3.0. My steps involve (I forgot about the update script):
- Download the new version
- Backup the data folder
- Unzip the new version into the grocy folder, overwriting the existing files

At this point I get the error `SQLSTATE[HY000]: General error: 1 near "OVER": syntax error` in the file `grocy/services/DatabaseService.php:37`

I was like OK, can happen, so I tried another update using the update script and I did:
- Install a clean version of the 3.1.3 release
- Copy my data folder over
- Check that it works
- Run the update script
- The update script finished successfully

The site shows the exact same error as above

Finally I tried a clean installation of version 3.3.0 by doing:
- Unpack the zip content into my grocy folder
- copy the `config-dist.php` to `data/config.php`

Load the site and it shows the same exact error as above

Here is the log it produces for copy pasting:

Error source:
```
/home/rolandd/webapps/grocy/services/DatabaseService.php:37
```

Error message:
```
SQLSTATE[HY000]: General error: 1 near "OVER": syntax error
```

Stack trace:
```
#0 /home/rolandd/webapps/grocy/services/DatabaseService.php(37): PDO->exec()
#1 /home/rolandd/webapps/grocy/services/DatabaseMigrationService.php(66): Grocy\Services\DatabaseService->ExecuteDbStatement()
#2 /home/rolandd/webapps/grocy/services/DatabaseMigrationService.php(36): Grocy\Services\DatabaseMigrationService->ExecuteSqlMigrationWhenNeeded()
#3 /home/rolandd/webapps/grocy/controllers/SystemController.php(27): Grocy\Services\DatabaseMigrationService->MigrateDatabase()
#4 /home/rolandd/webapps/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\Controllers\SystemController->Root()
#5 /home/rolandd/webapps/grocy/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
#6 /home/rolandd/webapps/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#7 /home/rolandd/webapps/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
#8 /home/rolandd/webapps/grocy/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#9 /home/rolandd/webapps/grocy/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#10 /home/rolandd/webapps/grocy/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#11 /home/rolandd/webapps/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\LocaleMiddleware->__invoke()
#12 /home/rolandd/webapps/grocy/middleware/AuthMiddleware.php(31): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#13 /home/rolandd/webapps/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\AuthMiddleware->__invoke()
#14 /home/rolandd/webapps/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#15 /home/rolandd/webapps/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#16 /home/rolandd/webapps/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#17 /home/rolandd/webapps/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#18 /home/rolandd/webapps/grocy/middleware/CorsMiddleware.php(30): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /home/rolandd/webapps/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\CorsMiddleware->__invoke()
#20 /home/rolandd/webapps/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /home/rolandd/webapps/grocy/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#22 /home/rolandd/webapps/grocy/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#23 /home/rolandd/webapps/grocy/app.php(106): Slim\App->run()
#24 /home/rolandd/webapps/grocy/public/index.php(45): require_once('...')
#25 {main}
```

System info:
```
{
    "grocy_version": {
        "Version": "3.3.0",
        "ReleaseDate": "2022-04-08"
    },
    "php_version": "8.0.16",
    "sqlite_version": "3.22.0",
    "os": "Linux 4.15.0-167-generic #175-Ubuntu SMP Wed Jan 5 01:56:07 UTC 2022 x86_64",
    "client": "Mozilla\/5.0 (X11; Linux x86_64; rv:99.0) Gecko\/20100101 Firefox\/99.0"
}
```
Hopefully you have enough info, otherwise please let me know and I will be happy to provide.

**Comment by berrnd** [comment]
> "sqlite_version": "3.22.0",

No real surprise that you get the same error in any case when using such an old SQLite version.

What's used at that point is a window function which was introduced in [SQLite 3.25.0](https://www.sqlite.org/changes.html#version_3_25_0) (release 3.5 years ago).

README excerpt](https://github.com/grocy/grocy#how-to-install):
> Currently everything is only tested against (means 100 % works with) PHP 8.0 with **SQLite 3.27.2**

So use quite up to date SQLite version and everything will work.

**Comment by roland-d** [comment]
Thank you @berrnd I did check the issues but missed the version part in the README. Contacted my host to update SQLite.
