### ISSUE TITLE
Bug: A server error occured using Button `add overdue/expired products`

### ISSUE THREAD

**Issue by dseegers** [grocy/grocy#1884]
When I have pressed the `add overdue/expired products` button. The Shopping list keeps throwing an server error. 

Steps to reproduce:
1. Add minimum for product to 1
2. Press  `add overdue/expired products` button in shopping list section
3. An error accured after pressing this button
4. After clicking on the shopping list you get the same error

Version info: 
**PHP Version**: 8.1.1
**SQLite Version**: 3.26.0
**OS**: Linux 3.10.0-962.3.2.lve1.5.50.el7.x86_64 #1 SMP Wed Mar 10 08:48:37 UTC 2021 x86_64
**Client**: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36
**Grocy release**: 3.3.0

**Error source** `/home/grocy/domains/grocy.domain.example/public_html/data/viewcache/433191fcce7a82c60a56a27b554aa180ba82fe29.php:250`

**Error message**
`Unsupported operand types: int * string (View: /home/grocy/domains/grocy.domain.example/public_html/views/shoppinglist.blade.php)`

```php 
#0 /home/grocy/domains/grocy.domain.example/public_html/vendor/illuminate/view/Engines/PhpEngine.php(60): Illuminate\View\Engines\CompilerEngine->handleViewException()
#1 /home/grocy/domains/grocy.domain.example/public_html/vendor/illuminate/view/Engines/CompilerEngine.php(61): Illuminate\View\Engines\PhpEngine->evaluatePath()
#2 /home/grocy/domains/grocy.domain.example/public_html/vendor/illuminate/view/View.php(139): Illuminate\View\Engines\CompilerEngine->get()
#3 /home/grocy/domains/grocy.domain.example/public_html/vendor/illuminate/view/View.php(122): Illuminate\View\View->getContents()
#4 /home/grocy/domains/grocy.domain.example/public_html/vendor/illuminate/view/View.php(91): Illuminate\View\View->renderContents()
#5 /home/grocy/domains/grocy.domain.example/public_html/vendor/berrnd/slim-blade-view/src/Blade.php(173): Illuminate\View\View->render()
#6 /home/grocy/domains/grocy.domain.example/public_html/vendor/berrnd/slim-blade-view/src/Blade.php(65): Slim\Views\Blade->fetch()
#7 /home/grocy/domains/grocy.domain.example/public_html/controllers/BaseController.php(180): Slim\Views\Blade->render()
#8 /home/grocy/domains/grocy.domain.example/public_html/controllers/BaseController.php(203): Grocy\Controllers\BaseController->render()
#9 /home/grocy/domains/grocy.domain.example/public_html/controllers/StockController.php(374): Grocy\Controllers\BaseController->renderPage()
#10 /home/grocy/domains/grocy.domain.example/public_html/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\Controllers\StockController->ShoppingList()
#11 /home/grocy/domains/grocy.domain.example/public_html/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
#12 /home/grocy/domains/grocy.domain.example/public_html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#13 /home/grocy/domains/grocy.domain.example/public_html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
#14 /home/grocy/domains/grocy.domain.example/public_html/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#15 /home/grocy/domains/grocy.domain.example/public_html/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#16 /home/grocy/domains/grocy.domain.example/public_html/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#17 /home/grocy/domains/grocy.domain.example/public_html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\LocaleMiddleware->__invoke()
#18 /home/grocy/domains/grocy.domain.example/public_html/middleware/AuthMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /home/grocy/domains/grocy.domain.example/public_html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\AuthMiddleware->__invoke()
#20 /home/grocy/domains/grocy.domain.example/public_html/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /home/grocy/domains/grocy.domain.example/public_html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#22 /home/grocy/domains/grocy.domain.example/public_html/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#23 /home/grocy/domains/grocy.domain.example/public_html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#24 /home/grocy/domains/grocy.domain.example/public_html/middleware/CorsMiddleware.php(30): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#25 /home/grocy/domains/grocy.domain.example/public_html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\CorsMiddleware->__invoke()
#26 /home/grocy/domains/grocy.domain.example/public_html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#27 /home/grocy/domains/grocy.domain.example/public_html/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#28 /home/grocy/domains/grocy.domain.example/public_html/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#29 /home/grocy/domains/grocy.domain.example/public_html/app.php(106): Slim\App->run()
#30 /home/grocy/domains/grocy.domain.example/public_html/public/index.php(45): require_once('/home/grocy/dom...')
#31 {main}
```
![image](https://user-images.githubusercontent.com/6848396/167291059-dba98630-e613-4809-89e6-7de9de67311a.png)

**Comment by berrnd** [comment]
Please provide a reproducible example, like also mentioned on the issue template - I can't reproduce that by the steps provided.

From the error message you most likely have a string where a number is expected, I doubt that's possible to get via the web frontend. Maybe you have inputted some bullshit via the API or whatever.

**Comment by dseegers** [comment]
I dug in and apparently a quantity unit was set that turned out to have no value, so the $productQuConversion->factor returned a string and cannot make a calculation.

**Comment by berrnd** [comment]
Thanks for providing the reproducible example.

> apparently a quantity unit was set that turned out to have no value

I guess you mean a unit conversion. That's, as guessed above, not possible via the frontend. grocy is generally based around the [GIGO principal](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out), means bullshit in = bullshit out. I'll change nothing about this particular "problem".

**Comment by berrnd** [comment]
Fixed by https://github.com/grocy/grocy/commit/00ac935367e6940bc9d81b26341b5bfd4f084105.
