### ISSUE TITLE
Feature Request: LDAP Auth: Don't enforce `givenName` attribute

### ISSUE THREAD

**Issue by haemka** [grocy/grocy#1888]
I'm using the minimal LDAP of my QNAP NAS which is based on OpenLDAP but does not offer any option to add additional attributes and does not set the `givenName` attribute for my user accounts. AFAIR the standard LDAP schema used for authentication in UNIX environments (rfc2307, which is also used here) doesn't enforce that attribute to be set but only the `gecos`.

The `LdapAuthMiddleware.php` got that attribute hardcoded. 

Error source:
```
/app/grocy/services/UsersService.php:7
```

Error message:
```
Grocy\Services\UsersService::CreateUser(): Argument #2 ($firstName) must be of type string, null given, called in /app/grocy/middleware/LdapAuthMiddleware.php on line 73
```

Stack trace:
```
#0 /app/grocy/middleware/LdapAuthMiddleware.php(73): Grocy\Services\UsersService->CreateUser()
#1 /app/grocy/controllers/LoginController.php(23): Grocy\Middleware\LdapAuthMiddleware::ProcessLogin()
#2 /app/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\Controllers\LoginController->ProcessLogin()
#3 /app/grocy/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
#4 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#5 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
#6 /app/grocy/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#7 /app/grocy/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#8 /app/grocy/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#9 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\LocaleMiddleware->__invoke()
#10 /app/grocy/middleware/AuthMiddleware.php(36): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#11 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\AuthMiddleware->__invoke()
#12 /app/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#13 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#14 /app/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#15 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#16 /app/grocy/middleware/CorsMiddleware.php(30): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#17 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\CorsMiddleware->__invoke()
#18 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /app/grocy/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#20 /app/grocy/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#21 /app/grocy/app.php(106): Slim\App->run()
#22 /app/grocy/public/index.php(45): require_once('...')
#23 {main}
```

System info:
```
{
    "grocy_version": {
        "Version": "3.3.0",
        "ReleaseDate": "2022-04-08"
    },
    "php_version": "8.0.13",
    "sqlite_version": "3.35.5",
    "os": "Linux 4.2.8 #2 SMP Thu Mar 24 07:15:40 CST 2022 armv7l",
    "client": "Mozilla\/5.0 (X11; Linux x86_64; rv:99.0) Gecko\/20100101 Firefox\/99.0"
}
```

**Comment by berrnd** [comment]
By having a quick look:
`givenName` is not in the scope of [rfc2307](https://datatracker.ietf.org/doc/html/rfc2307), but references [rfc2256](https://datatracker.ietf.org/doc/html/rfc2256) which doesn't say anything about if that attribute must be set or not.

The current implemention was tested against Windows Active Directory, OpenLDAP and GLAuth. I haven't personally seen any LDAP service where you can't set the first name, but of course you can leave it empty.

Whatever, we can of course change to not enforce to require that attribute.

**Comment by haemka** [comment]
Some additional info:
For now it helped to ldapmodify my user accounts and add the `givenName` attribute. With that modification grocy was able to create the users. So generally it works with this OpenLDAP implementation used by QNAP.

Nonetheless it would probably be nice to not enforce the `givenName` attribute and find the lowest common denominator between the standards to also support standalone rfc2307 and rfc2703bis out of the box.
