### ISSUE TITLE
Bug: An internal error occurred while processing your request

### ISSUE THREAD

**Issue by Jfmblinux** [grocy/grocy#1892]
Hello,

When I want to add items that I bought, it gives me errors.
An internal error occurred while processing your request

```
Error-source
/var/www/grocy/data/viewcache/96630a10a6a5f87b3ba7cca63fb636e7842d25eb.php:1
```

```
Error-message
Undefined constant "GROCY_FEATURE_FLAG_DISABLE_BROWSER_BARCODE_CAMERA_SCANNING" (View: /var/www/grocy/views/components/barcodescanner.blade.php) (View: /var/www/grocy/views/components/barcodescanner.blade.php)
```
![[Grocy Error](https://picture.jfmblinux.fr/uSZoPPq3/s4vl1Tdx.png)](https://picture.jfmblinux.fr/uSZoPPq3/s4vl1Tdx)

**Comment by Jfmblinux** [comment]
I am new in this field.

No I didn't modify any file, I don't see how we can do that?

**Comment by berrnd** [comment]
Whatever, I need a reproducible way to get this problem and then I'm happy to fix it, just like each and every problem since grocy exists.

By just having a screenshot that's impossible, or let me know if you know a way to fix things by that only.

**Comment by berrnd** [comment]
You even haven't mentioned which version you're running exactly and how you run grocy.

> No I didn't modify any file, I don't see how we can do that?

By that I guess you use any of the Docker images or something. A (every) file can normally be edited by opening it and do your thing. The only file that needs to edited regarding configuration stuff is `data/config.php` (as also [mentioned in README](https://github.com/grocy/grocy#how-to-install)).

**Comment by Jfmblinux** [comment]
Oh sorry.
I'm using version 3.3.0, but with Yunohost I didn't touch this `data/config.php` file.

**Comment by Jfmblinux** [comment]
Error source:
```
/var/www/grocy/data/viewcache/96630a10a6a5f87b3ba7cca63fb636e7842d25eb.php:1
```

Error message:
```
Undefined constant "GROCY_FEATURE_FLAG_DISABLE_BROWSER_BARCODE_CAMERA_SCANNING" (View: /var/www/grocy/views/components/barcodescanner.blade.php) (View: /var/www/grocy/views/components/barcodescanner.blade.php) (View: /var/www/grocy/views/components/barcodescanner.blade.php)
```

Stack trace:
```
#0 /var/www/grocy/vendor/illuminate/view/Engines/PhpEngine.php(60): Illuminate\View\Engines\CompilerEngine->handleViewException()
#1 /var/www/grocy/vendor/illuminate/view/Engines/CompilerEngine.php(61): Illuminate\View\Engines\PhpEngine->evaluatePath()
#2 /var/www/grocy/vendor/illuminate/view/View.php(139): Illuminate\View\Engines\CompilerEngine->get()
#3 /var/www/grocy/vendor/illuminate/view/View.php(122): Illuminate\View\View->getContents()
#4 /var/www/grocy/vendor/illuminate/view/View.php(91): Illuminate\View\View->renderContents()
#5 /var/www/grocy/vendor/berrnd/slim-blade-view/src/Blade.php(173): Illuminate\View\View->render()
#6 /var/www/grocy/vendor/berrnd/slim-blade-view/src/Blade.php(65): Slim\Views\Blade->fetch()
#7 /var/www/grocy/controllers/BaseController.php(180): Slim\Views\Blade->render()
#8 /var/www/grocy/controllers/BaseController.php(203): Grocy\Controllers\BaseController->render()
#9 /var/www/grocy/controllers/StockController.php(268): Grocy\Controllers\BaseController->renderPage()
#10 /var/www/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\Controllers\StockController->Purchase()
#11 /var/www/grocy/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
#12 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#13 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
#14 /var/www/grocy/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#15 /var/www/grocy/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#16 /var/www/grocy/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#17 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\LocaleMiddleware->__invoke()
#18 /var/www/grocy/middleware/AuthMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\AuthMiddleware->__invoke()
#20 /var/www/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#22 /var/www/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#23 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#24 /var/www/grocy/middleware/CorsMiddleware.php(30): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#25 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\CorsMiddleware->__invoke()
#26 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#27 /var/www/grocy/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#28 /var/www/grocy/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#29 /var/www/grocy/app.php(106): Slim\App->run()
#30 /var/www/grocy/public/index.php(45): require_once('...')
#31 {main}
```

System info:
```
{
    "grocy_version": {
        "Version": "3.3.0",
        "ReleaseDate": "2022-04-08"
    },
    "php_version": "8.0.18",
    "sqlite_version": "3.27.2",
    "os": "Linux 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64",
    "client": "Mozilla\/5.0 (X11; Linux x86_64; rv:100.0) Gecko\/20100101 Firefox\/100.0"
}
```

**Comment by berrnd** [comment]
That's just the same what is already mostly visible in your first screesnhot above.

I only can repeat what I've just said: Provide a reproducible example and I'm happy to fix it.

Most likely this is caused by configuration file fuckups, as also just mentioned above - the in the error mentioned missing constant [is there](https://github.com/grocy/grocy/blob/af7de61c43e250bf03f1a3209e96c19c5efa9e9e/config-dist.php#L147).

**Comment by berrnd** [comment]
All not in `data/config.php` existing options are taken from `config-dist.php` - so this can't be the problem. But when it works, whatever...

When you remove (or comment out `//`) anything in `config-dist.php`, this can cause such problems.

**Comment by Jfmblinux** [comment]
Ok no worries, I see indeed. I understand a little better.
There I just rechecked and no, nothing is disabled, I thought I had done it, but it works without any problem.

But adding `Setting('FEATURE_FLAG_DISABLE_BROWSER_BARCODE_CAMERA_SCANNING', false);` this solved the problem. So I guess (I'm just a little newbie) that must have been what was giving me the problem.
