### ISSUE TITLE
Bug: "SQLSTATE[HY000]: General error: 1 no such table: users" in a new Raspberry PI installation

### ISSUE THREAD

**Issue by peppe8o** [grocy/grocy#1918]
Just tried to install it on a fresh Raspberry PI OS Lite, after logging with the default admin user I get the above mentioned error.
Please find below the error logs from browser:

Error source:
```
/var/www/html/vendor/morris/lessql/src/LessQL/Database.php:108
```

Error message:
```
SQLSTATE[HY000]: General error: 1 no such table: users
```

Stack trace:
```
#0 /var/www/html/vendor/morris/lessql/src/LessQL/Database.php(108): PDO->prepare()
#1 /var/www/html/vendor/morris/lessql/src/LessQL/Database.php(491): LessQL\Database->prepare()
#2 /var/www/html/vendor/morris/lessql/src/LessQL/Result.php(149): LessQL\Database->select()
#3 /var/www/html/vendor/morris/lessql/src/LessQL/Result.php(322): LessQL\Result->execute()
#4 /var/www/html/middleware/DefaultAuthMiddleware.php(34): LessQL\Result->fetch()
#5 /var/www/html/controllers/LoginController.php(23): Grocy\Middleware\DefaultAuthMiddleware::ProcessLogin()
#6 /var/www/html/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\Controllers\LoginController->ProcessLogin()
#7 /var/www/html/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
#8 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#9 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
#10 /var/www/html/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#11 /var/www/html/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#12 /var/www/html/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#13 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\LocaleMiddleware->__invoke()
#14 /var/www/html/middleware/AuthMiddleware.php(36): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#15 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\AuthMiddleware->__invoke()
#16 /var/www/html/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#17 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#18 /var/www/html/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#20 /var/www/html/middleware/CorsMiddleware.php(30): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\CorsMiddleware->__invoke()
#22 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#23 /var/www/html/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#24 /var/www/html/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#25 /var/www/html/app.php(106): Slim\App->run()
#26 /var/www/html/public/index.php(45): require_once('...')
#27 {main}
```

System info:
```
{
    "grocy_version": {
        "Version": "3.3.1",
        "ReleaseDate": "2022-06-10"
    },
    "php_version": "8.0.20",
    "sqlite_version": "3.34.1",
    "os": "Linux 5.15.32-v7+ #1538 SMP Thu Mar 31 19:38:48 BST 2022 armv7l",
    "client": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:101.0) Gecko\/20100101 Firefox\/101.0"
}
```

**Comment by berrnd** [comment]
You haven't visited the root route (`/`), database migrations only run on that route ([README ref](https://github.com/grocy/grocy#database-migrations)).

**Comment by OthmanEmpire** [comment]
This error as I've just discovered if triggered if your `DocumentRoot` parameter (on Apache) has a trailing slash at the end. The Grocy login page still works but once you login, you see that the DB is not initialized properly. The fix is to remove the trailing slash and then things get initialized properly as @berrnd referenced in the post above.
