### ISSUE TITLE
Bug: Server error on pages recipes and mealplan after update to new version 3.2.0

### ISSUE THREAD

**Issue by juhagenah** [grocy/grocy#2052]
Error source:
```
/var/www/html/vhosts/grocy/vendor/morris/lessql/src/LessQL/Database.php:108
```

Error message:
```
SQLSTATE[HY000]: General error: 1 no such function: grocy_user_setting
```

Stack trace:
```
#0 /var/www/html/vhosts/grocy/vendor/morris/lessql/src/LessQL/Database.php(108): PDO->prepare()
#1 /var/www/html/vhosts/grocy/vendor/morris/lessql/src/LessQL/Database.php(491): LessQL\Database->prepare()
#2 /var/www/html/vhosts/grocy/vendor/morris/lessql/src/LessQL/Result.php(149): LessQL\Database->select()
#3 /var/www/html/vhosts/grocy/vendor/morris/lessql/src/LessQL/Result.php(654): LessQL\Result->execute()
#4 /var/www/html/vhosts/grocy/helpers/extensions.php(5): LessQL\Result->getIterator()
#5 /var/www/html/vhosts/grocy/controllers/RecipesController.php(94): FindObjectInArrayByPropertyValue()
#6 /var/www/html/vhosts/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\Controllers\RecipesController->Overview()
#7 /var/www/html/vhosts/grocy/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
#8 /var/www/html/vhosts/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#9 /var/www/html/vhosts/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
#10 /var/www/html/vhosts/grocy/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#11 /var/www/html/vhosts/grocy/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#12 /var/www/html/vhosts/grocy/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#13 /var/www/html/vhosts/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\LocaleMiddleware->__invoke()
#14 /var/www/html/vhosts/grocy/middleware/AuthMiddleware.php(76): class@anonymous->handle()
#15 /var/www/html/vhosts/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\AuthMiddleware->__invoke()
#16 /var/www/html/vhosts/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): class@anonymous->handle()
#17 /var/www/html/vhosts/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#18 /var/www/html/vhosts/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle()
#19 /var/www/html/vhosts/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#20 /var/www/html/vhosts/grocy/middleware/CorsMiddleware.php(30): class@anonymous->handle()
#21 /var/www/html/vhosts/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Grocy\Middleware\CorsMiddleware->__invoke()
#22 /var/www/html/vhosts/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle()
#23 /var/www/html/vhosts/grocy/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#24 /var/www/html/vhosts/grocy/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#25 /var/www/html/vhosts/grocy/app.php(106): Slim\App->run()
#26 /var/www/html/vhosts/grocy/public/index.php(45): require_once('/var/www/html/v...')
#27 {main}
```

System info:
```
{
    "grocy_version": {
        "Version": "3.2.0",
        "ReleaseDate": "2022-02-11"
    },
    "php_version": "7.4.30",
    "sqlite_version": "3.34.1",
    "os": "Linux 5.15.74+ #1595 Wed Oct 26 11:01:05 BST 2022 armv6l",
    "client": "Mozilla\/5.0 (X11; Linux x86_64; rv:107.0) Gecko\/20100101 Firefox\/107.0"
}
```

**Comment by berrnd** [comment]
The current version is [v3.3.2](https://grocy.info/changelog#v3.3.2), [v3.2.0](https://grocy.info/changelog#v3.2.0) was released 9 months - always only the current/latest version is supported.

Beside that: The mentioned missing function `grocy_user_setting` was added in 91b984d52dd8e42b2afc141105beb53ee2bb075b, which was committed on 2022-03-29. So this was never part of v3.2.0, which was release on 2022-02-11. I can't guess what you've done to get this, but it's unlikely you used the official release ZIP, which is to only supported way to run grocy.

**Comment by berrnd** [comment]
And please also note: Only PHP 8.0 is supported ([README ref](https://github.com/grocy/grocy#how-to-install)) since [v3.1.0](https://grocy.info/changelog#v3.1.0)

References #2038, #2044 and #2046.
