### ISSUE TITLE
Bug: demo change to https://zh-cn.demo.grocy.info/  error

### ISSUE THREAD

**Issue by importer** [grocy/grocy#2065]
Error source:
```
/var/www/demo.grocy.info/services/DatabaseService.php:37
```

Error message:
```
SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: users.username
```

Stack trace:
```
#0 /var/www/demo.grocy.info/services/DatabaseService.php(37): PDO->exec()
#1 /var/www/demo.grocy.info/services/DemoDataGeneratorService.php(206): Grocy\Services\DatabaseService->ExecuteDbStatement()
#2 /var/www/demo.grocy.info/controllers/SystemController.php(32): Grocy\Services\DemoDataGeneratorService->PopulateDemoData()
#3 /var/www/demo.grocy.info/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): Grocy\Controllers\SystemController->Root()
#4 /var/www/demo.grocy.info/vendor/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse->__invoke()
#5 /var/www/demo.grocy.info/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle()
#6 /var/www/demo.grocy.info/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\MiddlewareDispatcher->handle()
#7 /var/www/demo.grocy.info/vendor/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle()
#8 /var/www/demo.grocy.info/vendor/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run()
#9 /var/www/demo.grocy.info/middleware/AuthMiddleware.php(31): Slim\Routing\RouteRunner->handle()
#10 /var/www/demo.grocy.info/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\AuthMiddleware->__invoke()
#11 /var/www/demo.grocy.info/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(45): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#12 /var/www/demo.grocy.info/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\RoutingMiddleware->process()
#13 /var/www/demo.grocy.info/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#14 /var/www/demo.grocy.info/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process()
#15 /var/www/demo.grocy.info/middleware/CorsMiddleware.php(30): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#16 /var/www/demo.grocy.info/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\CorsMiddleware->__invoke()
#17 /var/www/demo.grocy.info/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#18 /var/www/demo.grocy.info/vendor/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle()
#19 /var/www/demo.grocy.info/vendor/slim/slim/Slim/App.php(183): Slim\App->handle()
#20 /var/www/demo.grocy.info/app.php(106): Slim\App->run()
#21 /var/www/demo.grocy.info/public/index.php(45): require_once('...')
#22 {main}
```

System info:
```
{
    "grocy_version": {
        "Version": "3.3.2",
        "ReleaseDate": "2022-11-12"
    },
    "php_version": "8.0.25",
    "sqlite_version": "3.34.1",
    "os": "Linux 5.15.74-1-pve #1 SMP PVE 5.15.74-1 (Mon, 14 Nov 2022 20:17:15 +0100) x86_64",
    "client": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/108.0.0.0 Safari\/537.36"
}
```

**Comment by berrnd** [comment]
That's a translation problem - translations are not maintained here (as [mentioned in README](https://github.com/grocy/grocy#localization)).

The original error message is:
```
SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: locations.name
```

Location names need to be unique, means someone has broken that for the `zh_CN` localization - feel free to fix it.

These are the mentioned demo localization strings:

https://github.com/grocy/grocy/blob/38a4ad8ec480c29a1bff057b3482fd103b036848/localization/demo_data.pot#L21-L31

https://github.com/grocy/grocy/blob/38a4ad8ec480c29a1bff057b3482fd103b036848/localization/demo_data.pot#L316-L317
