### ISSUE TITLE
Bug: Integrity constraint violation: 19 Provided qu_id doesn't have a related conversion for that product

### ISSUE THREAD

**Issue by L0ric0** [grocy/grocy#2153]
When trying to delete a Product from the meal_plan the error occures.
Somehow it is possible to not have quantity unit conversion for entrys in the meal_plan (i think the error does not only occure there) but the stacktrace is not realy helpfull (attached at the end). I think I have tracked it to the right Product but trying to add a quantity unit conversion for the corresponding quantity unit does not work with the same error.

Error source:
```
/usr/share/webapps/grocy/vendor/morris/lessql/src/LessQL/Database.php:754
```

Error message:
```
SQLSTATE[23000]: Integrity constraint violation: 19 Provided qu_id doesn't have a related conversion for that product
```
Stack trace:
```
#0 /usr/share/webapps/grocy/vendor/morris/lessql/src/LessQL/Database.php(754): PDOStatement->execute()
#1 /usr/share/webapps/grocy/vendor/morris/lessql/src/LessQL/Result.php(398): LessQL\\Database->delete()
#2 /usr/share/webapps/grocy/vendor/morris/lessql/src/LessQL/Row.php(441): LessQL\\Result->delete()
#3 /usr/share/webapps/grocy/controllers/GenericEntityApiController.php(104): LessQL\\Row->delete()
#4 /usr/share/webapps/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): Grocy\\Controllers\\GenericEntityApiController->DeleteObject()
#5 /usr/share/webapps/grocy/vendor/slim/slim/Slim/Routing/Route.php(358): Slim\\Handlers\\Strategies\\RequestResponse->__invoke()
#6 /usr/share/webapps/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\\Routing\\Route->handle()
#7 /usr/share/webapps/grocy/middleware/JsonMiddleware.php(13): Slim\\MiddlewareDispatcher->handle()
#8 /usr/share/webapps/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(168): Grocy\\Middleware\\JsonMiddleware->__invoke()
#9 /usr/share/webapps/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#10 /usr/share/webapps/grocy/vendor/slim/slim/Slim/Routing/Route.php(315): Slim\\MiddlewareDispatcher->handle()
#11 /usr/share/webapps/grocy/vendor/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\\Routing\\Route->run()
#12 /usr/share/webapps/grocy/middleware/LocaleMiddleware.php(16): Slim\\Routing\\RouteRunner->handle()
#13 /usr/share/webapps/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\\Middleware\\LocaleMiddleware->__invoke()
#14 /usr/share/webapps/grocy/middleware/AuthMiddleware.php(76): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#15 /usr/share/webapps/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\\Middleware\\AuthMiddleware->__invoke()
#16 /usr/share/webapps/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(45): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#17 /usr/share/webapps/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\\Middleware\\RoutingMiddleware->process()
#18 /usr/share/webapps/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#19 /usr/share/webapps/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\\Middleware\\ErrorMiddleware->process()
#20 /usr/share/webapps/grocy/middleware/CorsMiddleware.php(30): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#21 /usr/share/webapps/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\\Middleware\\CorsMiddleware->__invoke()
#22 /usr/share/webapps/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#23 /usr/share/webapps/grocy/vendor/slim/slim/Slim/App.php(199): Slim\\MiddlewareDispatcher->handle()
#24 /usr/share/webapps/grocy/vendor/slim/slim/Slim/App.php(183): Slim\\App->handle()
#25 /usr/share/webapps/grocy/app.php(106): Slim\\App->run()
#26 /usr/share/webapps/grocy/public/index.php(45): require_once('...')
#27 {main}
```
System info:
```
{
    \"grocy_version\": {
        \"Version\": \"3.3.2\",
        \"ReleaseDate\": \"2022-11-12\"
    },
    \"php_version\": \"8.2.2\",
    \"sqlite_version\": \"3.40.1\",
    \"os\": \"Linux 6.1.9-arch1-2 #1 SMP PREEMPT_DYNAMIC Fri, 03 Feb 2023 18:49:53 +0000 x86_64\",
    \"client\": \"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko\\/20100101 Firefox\\/110.0\"
}
```

**Comment by berrnd** [comment]
The issue template mentions to provide a reproducible example at best on a [private/persistent demo instance](https://www.reddit.com/r/grocy/comments/jwnk9b) - what do I need to do to make this reproducible to have any change to fix it?

The error message refers to this check:

https://github.com/grocy/grocy/blob/91700e7dae4b35c32c2483ce0837a714df87a398/migrations/0202.sql#L19-L24

This check happens on adding an recipe ingredient, but technically the meal plan is based on internal (nested) recipes and therefore the corresponding internal recipes are recreated on any meal plan change action.

This checks enforces when the recipe ingredient option "Only check if any amount is in stock" is checked (you can then selected any quantity unit for that product), that the selected unit needs to have a related unit conversion, since any calculations can't work without that. Was added for #2013.

Means, you have at least one recipe on your meal plan for that day or week where that's the case, when this happens when deleting a product from it. grocy generally follows the [GIGO principal](https://de.wikipedia.org/wiki/Garbage_In,_Garbage_Out) and that's then just that.

**Comment by L0ric0** [comment]
Ok thanks I will try to produce a reproducible exampel

**Comment by L0ric0** [comment]
Thanks for your help I was able to fix the issue by trying to delete all entrys in the meal plan. Sadly I'm unable to reproduce the issue so I will be closing this.
