### ISSUE TITLE
Bug: Unique constraint on migrations

### ISSUE THREAD

**Issue by thelegendtubaguy** [grocy/grocy#2279]
First time using this, spun up the LinuxServer docker container and got this error.

Error source:
```
/app/www/services/DatabaseService.php:37
```

Error message:
```
SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: migrations.migration
```

Stack trace:
```
#0 /app/www/services/DatabaseService.php(37): PDO->exec()
#1 /app/www/services/DatabaseMigrationService.php(75): Grocy\Services\DatabaseService->ExecuteDbStatement()
#2 /app/www/services/DatabaseMigrationService.php(35): Grocy\Services\DatabaseMigrationService->ExecuteSqlMigrationWhenNeeded()
#3 /app/www/controllers/SystemController.php(27): Grocy\Services\DatabaseMigrationService->MigrateDatabase()
#4 /app/www/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): Grocy\Controllers\SystemController->Root()
#5 /app/www/vendor/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse->__invoke()
#6 /app/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle()
#7 /app/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\MiddlewareDispatcher->handle()
#8 /app/www/vendor/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle()
#9 /app/www/vendor/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run()
#10 /app/www/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#11 /app/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\LocaleMiddleware->__invoke()
#12 /app/www/middleware/AuthMiddleware.php(31): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#13 /app/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\AuthMiddleware->__invoke()
#14 /app/www/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(45): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#15 /app/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\RoutingMiddleware->process()
#16 /app/www/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#17 /app/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process()
#18 /app/www/middleware/CorsMiddleware.php(30): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /app/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\CorsMiddleware->__invoke()
#20 /app/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /app/www/vendor/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle()
#22 /app/www/vendor/slim/slim/Slim/App.php(183): Slim\App->handle()
#23 /app/www/app.php(106): Slim\App->run()
#24 /app/www/public/index.php(45): require_once('...')
#25 {main}
```

System info:
```
{
    "grocy_version": {
        "Version": "3.3.2",
        "ReleaseDate": "2022-11-12"
    },
    "php_version": "8.2.8",
    "sqlite_version": "3.41.2",
    "os": "Linux 5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64",
    "client": "Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/114.0.0.0 Safari\/537.36"
}
```

**Comment by thelegendtubaguy** [comment]
Refreshed some minutes later and got a login screen.  Maybe the migrations weren't yet done?

**Comment by berrnd** [comment]
> spun up the LinuxServer docker container

None of the community contributed apps/tools/integrations are maintained here.

&nbsp;
> Maybe the migrations weren't yet done?

I can't say anything more detailed without having proper reproduction steps.
