### ISSUE TITLE
Bug: Version 4.0.0 Stock Overview page error

### ISSUE THREAD

**Issue by clove3am** [grocy/grocy#2281]
When updating from v3.3.2 to v4.0.0 the Stock Overview page displays the following error.

- Update process `chmod +x '/var/www/grocy/update.sh' && '/var/www/grocy/update.sh' && chown -R www-data:www-data '/var/www/grocy'`

Error source:
```
/var/www/grocy/packages/morris/lessql/src/LessQL/Database.php:108
```

Error message:
```
SQLSTATE[HY000]: General error: 1 no such column: active (View: /var/www/grocy/views/stockoverview.blade.php)
```

Stack trace:
```
#0 /var/www/grocy/packages/illuminate/view/Engines/PhpEngine.php(60): Illuminate\View\Engines\CompilerEngine->handleViewException()
#1 /var/www/grocy/packages/illuminate/view/Engines/CompilerEngine.php(61): Illuminate\View\Engines\PhpEngine->evaluatePath()
#2 /var/www/grocy/packages/illuminate/view/View.php(139): Illuminate\View\Engines\CompilerEngine->get()
#3 /var/www/grocy/packages/illuminate/view/View.php(122): Illuminate\View\View->getContents()
#4 /var/www/grocy/packages/illuminate/view/View.php(91): Illuminate\View\View->renderContents()
#5 /var/www/grocy/packages/berrnd/slim-blade-view/src/Blade.php(173): Illuminate\View\View->render()
#6 /var/www/grocy/packages/berrnd/slim-blade-view/src/Blade.php(65): Slim\Views\Blade->fetch()
#7 /var/www/grocy/controllers/BaseController.php(182): Slim\Views\Blade->render()
#8 /var/www/grocy/controllers/BaseController.php(205): Grocy\Controllers\BaseController->render()
#9 /var/www/grocy/controllers/StockController.php(123): Grocy\Controllers\BaseController->renderPage()
#10 /var/www/grocy/packages/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): Grocy\Controllers\StockController->Overview()
#11 /var/www/grocy/packages/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse->__invoke()
#12 /var/www/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle()
#13 /var/www/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\MiddlewareDispatcher->handle()
#14 /var/www/grocy/packages/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle()
#15 /var/www/grocy/packages/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run()
#16 /var/www/grocy/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#17 /var/www/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\LocaleMiddleware->__invoke()
#18 /var/www/grocy/middleware/AuthMiddleware.php(77): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /var/www/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\AuthMiddleware->__invoke()
#20 /var/www/grocy/packages/slim/slim/Slim/Middleware/RoutingMiddleware.php(45): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /var/www/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\RoutingMiddleware->process()
#22 /var/www/grocy/packages/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#23 /var/www/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process()
#24 /var/www/grocy/middleware/CorsMiddleware.php(27): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#25 /var/www/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\CorsMiddleware->__invoke()
#26 /var/www/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#27 /var/www/grocy/packages/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle()
#28 /var/www/grocy/packages/slim/slim/Slim/App.php(183): Slim\App->handle()
#29 /var/www/grocy/app.php(109): Slim\App->run()
#30 /var/www/grocy/public/index.php(45): require_once('...')
#31 {main}
```

System info:
```
{
    "grocy_version": {
        "Version": "4.0.0",
        "ReleaseDate": "2023-07-29"
    },
    "php_version": "8.2.7",
    "sqlite_version": "3.40.1",
    "os": "Linux 6.1.0-10-arm64 #1 SMP Debian 6.1.38-1 (2023-07-14) aarch64",
    "client": "Mozilla\/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/116.0.0.0 Safari\/537.36"
}
```

**Comment by berrnd** [comment]
The same "bug" report as always right after a new release is published...

You forgot to execute database migrations, this is automatically done when visiting the root route (`/`, simply click the logo on the left upper edge when you most likely otherwise access a specific page only, e.g. because of having a bookmark pointing to it or whatever) - that's also [mentioned in README](https://github.com/grocy/grocy#database-migrations).

&nbsp;
> "php_version": "8.2.7",

Do you even read what's [mentioned in README](https://github.com/grocy/grocy#platform-support) and on the [changelog](https://grocy.info/changelog#v4.0.0) regarding platform support or anything else?

README excerpt:
> Platform support:
> PHP 8.1 (with SQLite 3.34.0+)

Changelog excerpt:
> ⚠️ PHP 8.1 (with SQLite 3.34.0+) is from now on the only supported runtime version.
