### ISSUE TITLE
Bug: Stockoverview not working anymore after Upgrade to 4.0 (docker image)

### ISSUE THREAD

**Issue by muellthosbutler** [grocy/grocy#2284]
<!--
After docker-compose pull grocy is not working anymore. Here is the bug trace:
+++++++++++++++++++++++++++++
Error source:
```
/app/www/packages/morris/lessql/src/LessQL/Database.php:108
```

Error message:
```
SQLSTATE[HY000]: General error: 1 no such column: active (View: /app/www/views/stockoverview.blade.php)
```

Stack trace:
```
#0 /app/www/packages/illuminate/view/Engines/PhpEngine.php(60): Illuminate\View\Engines\CompilerEngine->handleViewException()
#1 /app/www/packages/illuminate/view/Engines/CompilerEngine.php(61): Illuminate\View\Engines\PhpEngine->evaluatePath()
#2 /app/www/packages/illuminate/view/View.php(139): Illuminate\View\Engines\CompilerEngine->get()
#3 /app/www/packages/illuminate/view/View.php(122): Illuminate\View\View->getContents()
#4 /app/www/packages/illuminate/view/View.php(91): Illuminate\View\View->renderContents()
#5 /app/www/packages/berrnd/slim-blade-view/src/Blade.php(173): Illuminate\View\View->render()
#6 /app/www/packages/berrnd/slim-blade-view/src/Blade.php(65): Slim\Views\Blade->fetch()
#7 /app/www/controllers/BaseController.php(182): Slim\Views\Blade->render()
#8 /app/www/controllers/BaseController.php(205): Grocy\Controllers\BaseController->render()
#9 /app/www/controllers/StockController.php(123): Grocy\Controllers\BaseController->renderPage()
#10 /app/www/packages/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): Grocy\Controllers\StockController->Overview()
#11 /app/www/packages/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse->__invoke()
#12 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle()
#13 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\MiddlewareDispatcher->handle()
#14 /app/www/packages/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle()
#15 /app/www/packages/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run()
#16 /app/www/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#17 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\LocaleMiddleware->__invoke()
#18 /app/www/middleware/AuthMiddleware.php(77): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\AuthMiddleware->__invoke()
#20 /app/www/packages/slim/slim/Slim/Middleware/RoutingMiddleware.php(45): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\RoutingMiddleware->process()
#22 /app/www/packages/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#23 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process()
#24 /app/www/middleware/CorsMiddleware.php(27): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#25 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\CorsMiddleware->__invoke()
#26 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#27 /app/www/packages/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle()
#28 /app/www/packages/slim/slim/Slim/App.php(183): Slim\App->handle()
#29 /app/www/app.php(109): Slim\App->run()
#30 /app/www/public/index.php(45): require_once('...')
#31 {main}
```

System info:
```
{
    "grocy_version": {
        "Version": "4.0.0",
        "ReleaseDate": "2023-07-29"
    },
    "php_version": "8.2.8",
    "sqlite_version": "3.41.2",
    "os": "Linux 5.10.0-23-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64",
    "client": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/115.0.0.0 Safari\/537.36"
}
```
-------------------------------------------------------

**Comment by berrnd** [comment]
Please do a little search beforehand and it's also just the same just like after every release - you both have ignored what's mentioned in README and on the changelog - quoting myself from https://github.com/grocy/grocy/issues/2281#issuecomment-1656838049:

You forgot to execute database migrations, this is automatically done when visiting the root route (`/`, simply click the logo on the left upper edge when you most likely otherwise access a specific page only, e.g. because of having a bookmark pointing to it or whatever) - that's also [mentioned in README](https://github.com/grocy/grocy#database-migrations).

&nbsp;
> "php_version": "8.2.8",

Do you even read what's [mentioned in README](https://github.com/grocy/grocy#platform-support) and on the [changelog](https://grocy.info/changelog#v4.0.0) regarding platform support or anything else?

README excerpt:
> Platform support:
> PHP 8.1 (with SQLite 3.34.0+)

Changelog excerpt:
> ⚠️ PHP 8.1 (with SQLite 3.34.0+) is from now on the only supported runtime version.

**Comment by muellthosbutler** [comment]
After doing the Database Migration all works fine. Apologies for not
reading beforehand and thus creating unnecessary work.

Best regards,

muellthosbutler

Bernd Bestel ***@***.***> schrieb am Mo., 31. Juli 2023,
08:38:

**Comment by ilsaul** [comment]
Hi, thank you for the information. When I search I find this and add information.
But I'm pretty sure the docker paradigm is that on redeploying the container, the container fixes itself.
Anyway I'm unlucky I can't access system management for another month so I can't fix the problem. Is there some way to do this using the interface?

**Comment by TurnrDev** [comment]
Hi,

I think I might be suffering the same or similar issue. When I visit `/` I get redirected to `stockoverview` which seems to give the 502 error.  Is there a way to manually run migrations? I don't need to have any useful php logs, not sure if grocy logs go somewhere else?

**Comment by berrnd** [comment]
A 502 error is more than clearly completely unrelated ("502 Bad Gateway" can only be something on an upstream webserver). And in any case: Still none of the community contributed apps/tools/integrations are maintained here. This is the place for reproducible bugs and feature requests ([README ref](https://github.com/grocy/grocy#questions--help--bug-reports--feature-requests)), so you're completely wrong here.

&nbsp;
> Is there a way to manually run migrations?

Of course, simply refer to README: https://github.com/grocy/grocy#database-migrations
