### ISSUE TITLE
Bug: The demo site cannot use simplified Chinese

### ISSUE THREAD

**Issue by alei643** [grocy/grocy#2324]
When I visit [pre-release demo](https://demo-prerelease.grocy.info/) and use Chinese(China) language , the page reported the following error

![2023-08-24_09-29](https://github.com/grocy/grocy/assets/38073408/8a3568b9-e18e-466f-8982-93a27ed95978)
Error source:
```
/var/www/demo-prerelease.grocy.info/services/DatabaseService.php:39
```

Error message:
```
SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: users.username
```

Stack trace:
```
#0 /var/www/demo-prerelease.grocy.info/services/DatabaseService.php(39): PDO->exec()
#1 /var/www/demo-prerelease.grocy.info/services/DemoDataGeneratorService.php(225): Grocy\Services\DatabaseService->ExecuteDbStatement()
#2 /var/www/demo-prerelease.grocy.info/controllers/SystemController.php(35): Grocy\Services\DemoDataGeneratorService->PopulateDemoData()
#3 /var/www/demo-prerelease.grocy.info/packages/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): Grocy\Controllers\SystemController->Root()
#4 /var/www/demo-prerelease.grocy.info/packages/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse->__invoke()
#5 /var/www/demo-prerelease.grocy.info/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle()
#6 /var/www/demo-prerelease.grocy.info/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\MiddlewareDispatcher->handle()
#7 /var/www/demo-prerelease.grocy.info/packages/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle()
#8 /var/www/demo-prerelease.grocy.info/packages/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run()
#9 /var/www/demo-prerelease.grocy.info/middleware/AuthMiddleware.php(32): Slim\Routing\RouteRunner->handle()
#10 /var/www/demo-prerelease.grocy.info/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\AuthMiddleware->__invoke()
#11 /var/www/demo-prerelease.grocy.info/packages/slim/slim/Slim/Middleware/RoutingMiddleware.php(45): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#12 /var/www/demo-prerelease.grocy.info/packages/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\RoutingMiddleware->process()
#13 /var/www/demo-prerelease.grocy.info/packages/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#14 /var/www/demo-prerelease.grocy.info/packages/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process()
#15 /var/www/demo-prerelease.grocy.info/middleware/CorsMiddleware.php(27): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#16 /var/www/demo-prerelease.grocy.info/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\CorsMiddleware->__invoke()
#17 /var/www/demo-prerelease.grocy.info/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#18 /var/www/demo-prerelease.grocy.info/packages/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle()
#19 /var/www/demo-prerelease.grocy.info/packages/slim/slim/Slim/App.php(183): Slim\App->handle()
#20 /var/www/demo-prerelease.grocy.info/app.php(112): Slim\App->run()
#21 /var/www/demo-prerelease.grocy.info/public/index.php(45): require_once('...')
#22 {main}
```

System info:
```
{
    "grocy_version": {
        "Version": "pre-release-8c21969b",
        "ReleaseDate": "2023-08-22 19:43:43"
    },
    "php_version": "8.2.8",
    "sqlite_version": "3.34.1",
    "os": "Linux 5.15.108-1-pve #1 SMP PVE 5.15.108-1 (2023-06-17T09:41Z) x86_64",
    "client": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/116.0.0.0 Safari\/537.36"
}
```

**Comment by berrnd** [comment]
Someone fucked up some demo data translations strings (not a problem for anyone, it's only about demo data translations and therefore not a bug) - very low priority for me.

**Comment by berrnd** [comment]
I "fixed" that now - simply ensure that locations, products and everything else have unique names in the [demo_data resource](https://github.com/grocy/grocy/blob/master/localization/demo_data.pot) ([Transifex ref](https://app.transifex.com/grocy/grocy/translate/#zh_CN/demo_data/171101157)).

For this case, "Fridge" and "Freezer" was translated the same - breaking the demo on purpose without any surprise.
