### ISSUE TITLE
Bug: SQLSTATE[HY000]: General error: 1 no such column: active (View: /app/www/views/stockoverview.blade.php)

### ISSUE THREAD

**Issue by Aliofredi** [grocy/grocy#2325]
Bist gestern lief Grocy noch problemlos, jetzt bekomme ich die folgende Fehlermeldung. 
Ich hoffe jemand kennt die Lösung !!! 
Danke vorab 

Error source:
```
/app/www/packages/morris/lessql/src/LessQL/Database.php:110
```

Error message:
```
SQLSTATE[HY000]: General error: 1 no such column: active (View: /app/www/views/products.blade.php)
```

Stack trace:
```
#0 /app/www/packages/illuminate/view/Engines/PhpEngine.php(60): Illuminate\View\Engines\CompilerEngine->handleViewException()
#1 /app/www/packages/illuminate/view/Engines/CompilerEngine.php(72): Illuminate\View\Engines\PhpEngine->evaluatePath()
#2 /app/www/packages/illuminate/view/View.php(195): Illuminate\View\Engines\CompilerEngine->get()
#3 /app/www/packages/illuminate/view/View.php(178): Illuminate\View\View->getContents()
#4 /app/www/packages/illuminate/view/View.php(147): Illuminate\View\View->renderContents()
#5 /app/www/packages/berrnd/slim-blade-view/src/Blade.php(173): Illuminate\View\View->render()
#6 /app/www/packages/berrnd/slim-blade-view/src/Blade.php(65): Slim\Views\Blade->fetch()
#7 /app/www/controllers/BaseController.php(186): Slim\Views\Blade->render()
#8 /app/www/controllers/BaseController.php(209): Grocy\Controllers\BaseController->render()
#9 /app/www/controllers/StockController.php(273): Grocy\Controllers\BaseController->renderPage()
#10 /app/www/packages/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): Grocy\Controllers\StockController->ProductsList()
#11 /app/www/packages/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse->__invoke()
#12 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle()
#13 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\MiddlewareDispatcher->handle()
#14 /app/www/packages/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle()
#15 /app/www/packages/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run()
#16 /app/www/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#17 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\LocaleMiddleware->__invoke()
#18 /app/www/middleware/AuthMiddleware.php(77): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\AuthMiddleware->__invoke()
#20 /app/www/packages/slim/slim/Slim/Middleware/RoutingMiddleware.php(45): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\RoutingMiddleware->process()
#22 /app/www/packages/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#23 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process()
#24 /app/www/middleware/CorsMiddleware.php(27): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#25 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\CorsMiddleware->__invoke()
#26 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#27 /app/www/packages/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle()
#28 /app/www/packages/slim/slim/Slim/App.php(183): Slim\App->handle()
#29 /app/www/app.php(112): Slim\App->run()
#30 /app/www/public/index.php(45): require_once('...')
#31 {main}
```

System info:
```
{
    "grocy_version": {
        "Version": "4.0.2",
        "ReleaseDate": "2023-08-19"
    },
    "php_version": "8.2.8",
    "sqlite_version": "3.41.2",
    "os": "Linux 4.4.302+ #64561 SMP Fri May 19 01:32:50 CST 2023 x86_64",
    "client": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/116.0.0.0 Safari\/537.36"
}
```

**Comment by berrnd** [comment]
> Ich hoffe jemand kennt die Lösung !!!

Ein ganz klein bissl suchen (oder die README lesen) vorab ist so gar keine Option, oder?

&nbsp;
> Bist gestern lief Grocy noch problemlos

Du hast wohl ein Update gemacht gestern, von alleine macht Grocy überhaupt nix - eine komplette Beschreibung von was man gemacht hilft meistens mehr, als gar keine - aber wie auch immer:

&nbsp;
Duplicate of #2284 and #2281 and #2288 - quoting myself from https://github.com/grocy/grocy/issues/2281#issuecomment-1656838049:

You forgot to execute database migrations, this is automatically done when visiting the root route (`/`, simply click the logo on the left upper edge when you most likely otherwise access a specific page only, e.g. because of having a bookmark pointing to it or whatever) - that's also [mentioned in README](https://github.com/grocy/grocy#database-migrations).

**Comment by berrnd** [comment]
> Insofern danke für die Antwort, aber helfen tut sie mir persönlich leider nicht.

Also wenn das lesen meiner Antwort auch zu viel ist, dann tuts mir wirklich auch leid - ich bins leid und solche Anfragen frustrieren und nehmen mir aktuell und schon länger die Lust an diesem Projekt, aber das ist natürlich mein Problem.

Nochmal:

### Klick auf das scheiß Logo oben links und dein Problem ist behoben!!!
Wenn dafür vorab ein mehrjähriges technisches Studium oder ähnliches notwendig ist, dann musst das halt wohl machen.

![grafik](https://github.com/grocy/grocy/assets/2161815/956ebbeb-78ce-441f-9847-c5c41c089b88)

![grafik](https://github.com/grocy/grocy/assets/2161815/51b8918c-cf3c-436a-9c9c-d75e4aec3887)

![grafik](https://github.com/grocy/grocy/assets/2161815/fe18608b-bf70-4c98-88b6-43eadab84795)
