### ISSUE TITLE
Bug: LocalizationService.php Unknown format specifier " "

### ISSUE THREAD

**Issue by Nick4154** [grocy/grocy#2389]
It looks like there is a problem with translations, it happens quite randomly, after a while installing grocy. The interface is in french if that helps. Changing to English does not solve the problem.

Error source:
```
/var/www/html/services/LocalizationService.php:85
```

Error message:
```
Unknown format specifier " " (View: /var/www/html/views/shoppinglist.blade.php)
```

Stack trace:
```
#0 /var/www/html/packages/illuminate/view/Engines/PhpEngine.php(60): Illuminate\View\Engines\CompilerEngine->handleViewException()
#1 /var/www/html/packages/illuminate/view/Engines/CompilerEngine.php(72): Illuminate\View\Engines\PhpEngine->evaluatePath()
#2 /var/www/html/packages/illuminate/view/View.php(195): Illuminate\View\Engines\CompilerEngine->get()
#3 /var/www/html/packages/illuminate/view/View.php(178): Illuminate\View\View->getContents()
#4 /var/www/html/packages/illuminate/view/View.php(147): Illuminate\View\View->renderContents()
#5 /var/www/html/packages/berrnd/slim-blade-view/src/Blade.php(173): Illuminate\View\View->render()
#6 /var/www/html/packages/berrnd/slim-blade-view/src/Blade.php(65): Slim\Views\Blade->fetch()
#7 /var/www/html/controllers/BaseController.php(186): Slim\Views\Blade->render()
#8 /var/www/html/controllers/BaseController.php(209): Grocy\Controllers\BaseController->render()
#9 /var/www/html/controllers/StockController.php(395): Grocy\Controllers\BaseController->renderPage()
#10 /var/www/html/packages/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): Grocy\Controllers\StockController->ShoppingList()
#11 /var/www/html/packages/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse->__invoke()
#12 /var/www/html/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle()
#13 /var/www/html/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\MiddlewareDispatcher->handle()
#14 /var/www/html/packages/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle()
#15 /var/www/html/packages/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run()
#16 /var/www/html/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#17 /var/www/html/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\LocaleMiddleware->__invoke()
#18 /var/www/html/middleware/AuthMiddleware.php(77): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /var/www/html/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\AuthMiddleware->__invoke()
#20 /var/www/html/packages/slim/slim/Slim/Middleware/RoutingMiddleware.php(45): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /var/www/html/packages/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\RoutingMiddleware->process()
#22 /var/www/html/packages/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#23 /var/www/html/packages/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process()
#24 /var/www/html/middleware/CorsMiddleware.php(27): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#25 /var/www/html/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\CorsMiddleware->__invoke()
#26 /var/www/html/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#27 /var/www/html/packages/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle()
#28 /var/www/html/packages/slim/slim/Slim/App.php(183): Slim\App->handle()
#29 /var/www/html/app.php(112): Slim\App->run()
#30 /var/www/html/public/index.php(45): require_once('...')
#31 {main}
```

System info:
```
{
    "grocy_version": {
        "Version": "4.0.3",
        "ReleaseDate": "2023-09-02"
    },
    "php_version": "8.2.7",
    "sqlite_version": "3.40.1",
    "os": "Linux 6.2.16-19-pve #1 SMP PREEMPT_DYNAMIC PMX 6.2.16-19 (2023-10-24T12:07Z) x86_64",
    "client": "Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:120.0) Gecko\/20100101 Firefox\/120.0"
}
```

**Comment by berrnd** [comment]
Then please be so kind and provide a specific reproducible example, that's also mentioned on the issue template and I really don't get what you expect I should be able to solve by "sometimes something doesn't work, maybe related to the french translation".

There is even [demo instance](https://demo-prerelease.grocy.info) for each and every localization, of course something like that could also be caused by fucked up translation strings - those can be [edited by anyone on this planet](https://github.com/grocy/grocy#localization) and naturally I can't check each and every translated string for every of the currently 40 contributed localizations.

Quantity unit singular/plural handling also uses the same translation tech to display them, so maybe have a quick triple check on them.
