### ISSUE TITLE
Grocy new install on Portainer - Database.php:110 

### ISSUE THREAD

**Issue by alberkani** [grocy/grocy#2449]
Error source:
```
/app/www/packages/morris/lessql/src/LessQL/Database.php:110
```

Error message:
```
SQLSTATE[HY000]: General error: 1 no such table: users
```

Stack trace:
```
#0 /app/www/packages/morris/lessql/src/LessQL/Database.php(110): PDO->prepare()
#1 /app/www/packages/morris/lessql/src/LessQL/Database.php(493): LessQL\Database->prepare()
#2 /app/www/packages/morris/lessql/src/LessQL/Result.php(143): LessQL\Database->select()
#3 /app/www/packages/morris/lessql/src/LessQL/Result.php(322): LessQL\Result->execute()
#4 /app/www/middleware/DefaultAuthMiddleware.php(34): LessQL\Result->fetch()
#5 /app/www/controllers/LoginController.php(25): Grocy\Middleware\DefaultAuthMiddleware::ProcessLogin()
#6 /app/www/packages/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): Grocy\Controllers\LoginController->ProcessLogin()
#7 /app/www/packages/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse->__invoke()
#8 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle()
#9 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\MiddlewareDispatcher->handle()
#10 /app/www/packages/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle()
#11 /app/www/packages/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run()
#12 /app/www/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#13 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\LocaleMiddleware->__invoke()
#14 /app/www/middleware/AuthMiddleware.php(37): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#15 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\AuthMiddleware->__invoke()
#16 /app/www/packages/slim/slim/Slim/Middleware/RoutingMiddleware.php(45): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#17 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\RoutingMiddleware->process()
#18 /app/www/packages/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process()
#20 /app/www/middleware/CorsMiddleware.php(27): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\CorsMiddleware->__invoke()
#22 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#23 /app/www/packages/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle()
#24 /app/www/packages/slim/slim/Slim/App.php(183): Slim\App->handle()
#25 /app/www/app.php(112): Slim\App->run()
#26 /app/www/public/index.php(45): require_once('...')
#27 {main}
```

**Comment by berrnd** [comment]
None of the community contributed apps/tools/integrations/Docker images are maintained here.

**Comment by alberkani** [comment]
Can't you just let someone else try to answer my question instead of closing my post?
Looks like you enjoy expressing your virtual frustration with Grossy  crap  that is not working at all !  Good luck frustreikenstein !
