### ISSUE TITLE
Bug: /data/grocy/viewcache/fbf71db0bf421e50b4f55fb6c45f4d10.php:254

### ISSUE THREAD

**Issue by krefi1996** [grocy/grocy#2475]
Error source:
```
/data/grocy/viewcache/fbf71db0bf421e50b4f55fb6c45f4d10.php:254
```

Error message:
```
Unsupported operand types: string * string (View: /var/www/grocy/views/shoppinglist.blade.php)
```

Stack trace:
```
#0 /var/www/grocy/packages/illuminate/view/Engines/PhpEngine.php(60): Illuminate\View\Engines\CompilerEngine->handleViewException()
#1 /var/www/grocy/packages/illuminate/view/Engines/CompilerEngine.php(72): Illuminate\View\Engines\PhpEngine->evaluatePath()
#2 /var/www/grocy/packages/illuminate/view/View.php(195): Illuminate\View\Engines\CompilerEngine->get()
#3 /var/www/grocy/packages/illuminate/view/View.php(178): Illuminate\View\View->getContents()
#4 /var/www/grocy/packages/illuminate/view/View.php(147): Illuminate\View\View->renderContents()
#5 /var/www/grocy/packages/berrnd/slim-blade-view/src/Blade.php(173): Illuminate\View\View->render()
#6 /var/www/grocy/packages/berrnd/slim-blade-view/src/Blade.php(65): Slim\Views\Blade->fetch()
#7 /var/www/grocy/controllers/BaseController.php(186): Slim\Views\Blade->render()
#8 /var/www/grocy/controllers/BaseController.php(209): Grocy\Controllers\BaseController->render()
#9 /var/www/grocy/controllers/StockController.php(395): Grocy\Controllers\BaseController->renderPage()
#10 /var/www/grocy/packages/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): Grocy\Controllers\StockController->ShoppingList()
#11 /var/www/grocy/packages/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse->__invoke()
#12 /var/www/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle()
#13 /var/www/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\MiddlewareDispatcher->handle()
#14 /var/www/grocy/packages/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle()
#15 /var/www/grocy/packages/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run()
#16 /var/www/grocy/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#17 /var/www/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\LocaleMiddleware->__invoke()
#18 /var/www/grocy/middleware/AuthMiddleware.php(77): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /var/www/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\AuthMiddleware->__invoke()
#20 /var/www/grocy/packages/slim/slim/Slim/Middleware/RoutingMiddleware.php(45): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /var/www/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\RoutingMiddleware->process()
#22 /var/www/grocy/packages/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#23 /var/www/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process()
#24 /var/www/grocy/middleware/CorsMiddleware.php(27): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#25 /var/www/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\CorsMiddleware->__invoke()
#26 /var/www/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#27 /var/www/grocy/packages/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle()
#28 /var/www/grocy/packages/slim/slim/Slim/App.php(183): Slim\App->handle()
#29 /var/www/grocy/app.php(112): Slim\App->run()
#30 /var/www/grocy/public/index.php(45): require_once('...')
#31 {main}
```

System info:
```
{
    "grocy_version": {
        "Version": "4.0.3",
        "ReleaseDate": "2023-09-02"
    },
    "php_version": "8.2.14",
    "sqlite_version": "3.44.2",
    "os": "Linux 6.1.63-haos-raspi #1 SMP PREEMPT Mon Feb  5 11:40:23 UTC 2024 aarch64",
    "client": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/121.0.0.0 Safari\/537.36"
}
```

**Comment by berrnd** [comment]
Please be so kind and do a little search before opening new requests, that's also mentioned on the issue template.

Have a look at #1900 and all the other referenced threads. You most likely have somehow fucked up a shopping list entry, essentially having string where a number is expected (potentially the amount of any shopping list item). Getting this is not possible via the API, but maybe via the API (which e.g. also any third party tool uses).

**Comment by berrnd** [comment]
I've added #2657 which tracks to finally prevent this old mystery obviously not solvable at the origin source (since years).
