### ISSUE TITLE
Bug: SQLSTATE[HY000]: General error: 1 duplicate column name: qu_id_consume

### ISSUE THREAD

**Issue by mata-hari** [grocy/grocy#2487]
I've made a new installation under ubuntu-23.04\apache2\php8.2. If I try to start grocy I've the error message:
SQLSTATE[HY000]: General error: 1 duplicate column name: qu_id_consume
This is the error-reporting:
Error source:
```
/var/www/html/services/DatabaseService.php:42
```

Error message:
```
SQLSTATE[HY000]: General error: 1 duplicate column name: qu_id_consume
```

Stack trace:
```
#0 /var/www/html/services/DatabaseService.php(42): PDO->exec()
#1 /var/www/html/services/DatabaseMigrationService.php(69): Grocy\Services\DatabaseService->ExecuteDbStatement()
#2 /var/www/html/services/DatabaseMigrationService.php(35): Grocy\Services\DatabaseMigrationService->ExecuteSqlMigrationWhenNeeded()
#3 /var/www/html/controllers/SystemController.php(30): Grocy\Services\DatabaseMigrationService->MigrateDatabase()
#4 /var/www/html/packages/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): Grocy\Controllers\SystemController->Root()
#5 /var/www/html/packages/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse->__invoke()
#6 /var/www/html/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle()
#7 /var/www/html/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\MiddlewareDispatcher->handle()
#8 /var/www/html/packages/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle()
#9 /var/www/html/packages/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run()
#10 /var/www/html/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#11 /var/www/html/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\LocaleMiddleware->__invoke()
#12 /var/www/html/middleware/AuthMiddleware.php(32): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#13 /var/www/html/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\AuthMiddleware->__invoke()
#14 /var/www/html/packages/slim/slim/Slim/Middleware/RoutingMiddleware.php(45): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#15 /var/www/html/packages/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\RoutingMiddleware->process()
#16 /var/www/html/packages/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#17 /var/www/html/packages/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process()
#18 /var/www/html/middleware/CorsMiddleware.php(27): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /var/www/html/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\CorsMiddleware->__invoke()
#20 /var/www/html/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /var/www/html/packages/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle()
#22 /var/www/html/packages/slim/slim/Slim/App.php(183): Slim\App->handle()
#23 /var/www/html/app.php(112): Slim\App->run()
#24 /var/www/html/public/index.php(45): require_once('...')
#25 {main}
```

System info:
```
{
    "grocy_version": {
        "Version": "4.1.0",
        "ReleaseDate": "2024-02-09"
    },
    "php_version": "8.2.15",
    "sqlite_version": "3.40.1",
    "os": "Linux 5.15.64-1-pve #1 SMP PVE 5.15.64-1 (Thu, 13 Oct 2022 10:30:34 +0200) x86_64",
    "client": "Mozilla\/5.0 (Windows NT 6.1; Win64; x64; rv:109.0) Gecko\/20100101 Firefox\/115.0"
}
```

**Comment by mata-hari** [comment]
Sorry, after restarting the server the error-message didn't come again?

**Comment by berrnd** [comment]
Then you did something wrong, the column in question is clearly added only once ([there](https://github.com/grocy/grocy/blob/e01e0f3abe85945f8fac3ee2117dcbeb4a4e90aa/migrations/0210.sql#L1-L2)), not multiple times.

The [pre-release demo](https://demo-prerelease.grocy.info/) does a complete reset / re-installation each single hour, every day, since years - so this is reproducible not a bug.

**Comment by berrnd** [comment]
> Sorry, after restarting the server the error-message didn't come again?

Cool. Opening a bug report without investing a single minute in checking what the cause could be on your own, loving it!
