### ISSUE TITLE
Bug: Android App crashes when adding a new product group

### ISSUE THREAD

**Issue by Sch-Tim** [grocy/grocy#2488]
**System:**
Server version: 4.1.0
Android App version: 3.5.1

**Bug description:**
When I add a new product group using the Android app, the app crashes. 
The new group is still added successfully. 

**Crash report:**
```
--------- beginning of crash
03-04 16:28:42.229 19470 19470 E AndroidRuntime: FATAL EXCEPTION: main
03-04 16:28:42.229 19470 19470 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 19470
03-04 16:28:42.229 19470 19470 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'androidx.core.view.WindowInsetsAnimationCompat$Impl androidx.core.view.WindowInsetsAnimationCompat.mImpl' on a null object reference in method 'androidx.core.view.WindowInsetsCompat xyz.zedler.patrick.grocy.util.UiUtil$1.onProgress(androidx.core.view.WindowInsetsCompat, java.util.List)'
03-04 16:28:42.229 19470 19470 E AndroidRuntime: at xyz.zedler.patrick.grocy.util.UiUtil$1.onProgress(UiUtil.java:13)
03-04 16:28:42.229 19470 19470 E AndroidRuntime: at androidx.core.view.WindowInsetsAnimationCompat$Impl30$ProxyCallback.onProgress(WindowInsetsAnimationCompat.java:72)
03-04 16:28:42.229 19470 19470 E AndroidRuntime: at android.view.View.dispatchWindowInsetsAnimationProgress(View.java:12416)
03-04 16:28:42.229 19470 19470 E AndroidRuntime: at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7981)
03-04 16:28:42.229 19470 19470 E AndroidRuntime: at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7987)
03-04 16:28:42.229 19470 19470 E AndroidRuntime: at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7987)
03-04 16:28:42.229 19470 19470 E AndroidRuntime: at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7987)
03-04 16:28:42.229 19470 19470 E AndroidRuntime: at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7987)
03-04 16:28:42.229 19470 19470 E AndroidRuntime: at android.view.ViewGroup.dispatchWindowInsetsAnimationProgress(ViewGroup.java:7987)
03-04 16:28:42.229 19470 19470 E AndroidRuntime: at android.view.ViewRootInsetsControllerHost.dispatchWindowInsetsAnimationProgress(ViewRootInsetsControllerHost.java:112)
03-04 16:28:42.229 19470 19470 E AndroidRuntime: at android.view.InsetsController.lambda$new$3(InsetsController.java:922)
03-04 16:28:42.229 19470 19470 E AndroidRuntime: at android.view.InsetsController.$r8$lambda$Amx-Vld7pHmp7sZLsnZeliqd_HE(Unknown Source:0)
03-04 16:28:42.229 19470 19470 E AndroidRuntime: at android.view.InsetsController$$ExternalSyntheticLambda11.run(Unknown Source:2)
03-04 16:28:42.229 19470 19470 E AndroidRuntime: at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1650)
03-04 16:28:42.229 19470 19470 E AndroidRuntime: at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1659)
03-04 16:28:42.229 19470 19470 E AndroidRuntime: at android.view.Choreographer.doCallbacks(Choreographer.java:1129)
03-04 16:28:42.229 19470 19470 E AndroidRuntime: at android.view.Choreographer.doFrame(Choreographer.java:1051)
03-04 16:28:42.229 19470 19470 E AndroidRuntime: at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1622)
03-04 16:28:42.229 19470 19470 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:958)
03-04 16:28:42.229 19470 19470 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:99)
03-04 16:28:42.229 19470 19470 E AndroidRuntime: at android.os.Looper.loopOnce(Looper.java:230)
03-04 16:28:42.229 19470 19470 E AndroidRuntime: at android.os.Looper.loop(Looper.java:319)
03-04 16:28:42.229 19470 19470 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:8893)
03-04 16:28:42.229 19470 19470 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
03-04 16:28:42.229 19470 19470 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
03-04 16:28:42.229 19470 19470 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
--------- beginning of main
03-04 16:28:43.751 19603 19603 E r.patrick.grocy: Not starting debugger since process cannot load the jdwp agent.
03-04 16:28:46.254 19603 19603 E AnimationUtils: RuntimeException for unknown animation name, resouce ID #0x7f020028
03-04 16:28:46.254 19603 19603 E AnimationUtils: loadAnimation: getConfiguration = {1.1 262mcc7mnc [de_DE] ldltr sw384dp w384dp h774dp 450dpi nrml long port night finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 1080, 2400) mAppBounds=Rect(0, 88 - 1080, 2265) mMaxBounds=Rect(0, 0 - 1080, 2400) mDisplayRotation=ROTATION_0 mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=standard mAlwaysOnTop=undefined mRotation=ROTATION_0 mPopOver=offmOverlappingWithCutout=false mStageConfig=undefined mFreeformTaskPinningState=unpinned} s.1 fontWeightAdjustment=0 ff=0 bf=0 bts=0 cst=1.0 nightDim=0 themeSeq=0}
03-04 16:28:46.254 19603 19603 E AnimationUtils: loadAnimation: getDisplayMetrics = DisplayMetrics{density=2.8125, width=1080, height=2177, scaledDensity=3.09375, xdpi=409.432, ydpi=406.4}
03-04 16:28:46.254 19603 19603 E AnimationUtils: loadAnimation: resourceName = xyz.zedler.patrick.grocy:animator/open_enter
03-04 16:28:47.326 19603 19603 E AnimationUtils: RuntimeException for unknown animation name, resouce ID #0x7f020029
03-04 16:28:47.326 19603 19603 E AnimationUtils: loadAnimation: getConfiguration = {1.1 262mcc7mnc [de_DE] ldltr sw384dp w384dp h774dp 450dpi nrml long port night finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 1080, 2400) mAppBounds=Rect(0, 88 - 1080, 2265) mMaxBounds=Rect(0, 0 - 1080, 2400) mDisplayRotation=ROTATION_0 mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=standard mAlwaysOnTop=undefined mRotation=ROTATION_0 mPopOver=offmOverlappingWithCutout=false mStageConfig=undefined mFreeformTaskPinningState=unpinned} s.1 fontWeightAdjustment=0 ff=0 bf=0 bts=0 cst=1.0 nightDim=0 themeSeq=0}
03-04 16:28:47.326 19603 19603 E AnimationUtils: loadAnimation: getDisplayMetrics = DisplayMetrics{density=2.8125, width=1080, height=2177, scaledDensity=3.09375, xdpi=409.432, ydpi=406.4}
03-04 16:28:47.326 19603 19603 E AnimationUtils: loadAnimation: resourceName = xyz.zedler.patrick.grocy:animator/open_exit
```

**Comment by berrnd** [comment]
None of the community contributed apps/tools/integrations are maintained here.
