### ISSUE TITLE
Bug: No shopping list view after upgrading to 4.2.0

### ISSUE THREAD

**Issue by HaiQ31** [grocy/grocy#2498]
Hi,
after upgrading to grocy 4.2.0 I can no longer see the shopping lists. Instead I see an error message that says:
Error source:
```
/app/www/packages/morris/lessql/src/LessQL/Database.php:110
```

Error message:
```
SQLSTATE[HY000]: General error: 1 no such table: shopping_lists_view (View: /app/www/views/shoppinglist.blade.php)
```

Stack trace:
```
#0 /app/www/packages/illuminate/view/Engines/PhpEngine.php(60): Illuminate\View\Engines\CompilerEngine->handleViewException()
#1 /app/www/packages/illuminate/view/Engines/CompilerEngine.php(72): Illuminate\View\Engines\PhpEngine->evaluatePath()
#2 /app/www/packages/illuminate/view/View.php(207): Illuminate\View\Engines\CompilerEngine->get()
#3 /app/www/packages/illuminate/view/View.php(190): Illuminate\View\View->getContents()
#4 /app/www/packages/illuminate/view/View.php(159): Illuminate\View\View->renderContents()
#5 /app/www/packages/berrnd/slim-blade-view/src/Blade.php(173): Illuminate\View\View->render()
#6 /app/www/packages/berrnd/slim-blade-view/src/Blade.php(65): Slim\Views\Blade->fetch()
#7 /app/www/controllers/BaseController.php(186): Slim\Views\Blade->render()
#8 /app/www/controllers/BaseController.php(209): Grocy\Controllers\BaseController->render()
#9 /app/www/controllers/StockController.php(395): Grocy\Controllers\BaseController->renderPage()
#10 /app/www/packages/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): Grocy\Controllers\StockController->ShoppingList()
#11 /app/www/packages/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse->__invoke()
#12 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle()
#13 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\MiddlewareDispatcher->handle()
#14 /app/www/packages/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle()
#15 /app/www/packages/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run()
#16 /app/www/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#17 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\LocaleMiddleware->__invoke()
#18 /app/www/middleware/AuthMiddleware.php(77): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\AuthMiddleware->__invoke()
#20 /app/www/packages/slim/slim/Slim/Middleware/RoutingMiddleware.php(45): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\RoutingMiddleware->process()
#22 /app/www/packages/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#23 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process()
#24 /app/www/middleware/CorsMiddleware.php(27): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#25 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\CorsMiddleware->__invoke()
#26 /app/www/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#27 /app/www/packages/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle()
#28 /app/www/packages/slim/slim/Slim/App.php(183): Slim\App->handle()
#29 /app/www/app.php(112): Slim\App->run()
#30 /app/www/public/index.php(45): require_once('...')
#31 {main}
```

System info:
```
{
    "grocy_version": {
        "Version": "4.2.0",
        "ReleaseDate": "2024-03-15"
    },
    "php_version": "8.3.4",
    "sqlite_version": "3.44.2",
    "os": "Linux 4.4.302+ #69057 SMP Mon Nov 13 14:19:30 CST 2023 x86_64",
    "client": "Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko\/20100101 Firefox\/123.0"
}
```
			
I run grocy as Linux Server docker image.

**Comment by berrnd** [comment]
After each and every release, I start a bet how long it takes until the first one pops up who can't read READMEs this time - congrats, you're the winner for v4.2.0.

You forgot to execute database migrations, this is automatically done when visiting the root route (`/`, simply click the logo on the left upper edge when you most likely otherwise access a specific page only, e.g. because of having a bookmark pointing to it or whatever) - that's also [mentioned in README](https://github.com/grocy/grocy#database-migrations).

**Comment by HaiQ31** [comment]
First of all: Thank you for your work and this project. I like it a lot.
Thank you for your quick and more than kind reply. Indeed that solved my issue.

However: Of course I read the release notes before every update. I wasn't aware that a recurring task like database migration had to be triggered manually after every update. Many thanks for the advice. Perhaps a corresponding note as a fixed component in the release notes would be helpful to reduce the noise here. Sorry for the inconvenience.

**Comment by berrnd** [comment]
What needs to be done after doing an update hasn't really changed since about 7 years and about 75 releases and of course everything is mentioned at a glance in README (also since the same amount of time): https://github.com/grocy/grocy?tab=readme-ov-file#how-to-update

And no, I won't add this (then to essentially every single change) on the release notes. The same people who can't read READMEs (I don't get why this is so hard) also can't read release notes. Just check all the reports here and on the r/grocy subreddit about just that.

But since I'm tired of those kind of people, I'm [considering fully automating this really hard job](2384) (if I ever come back really enjoying working on this project, most likely this won't be a thing in 2024).
