### ISSUE TITLE
Bug: Integrity constraint violation: 19 Unsupported product nesting level detected

### ISSUE THREAD

**Issue by rockermeier** [grocy/grocy#2542]
I updated grocy to the latest version (4.2.0) together with php from 7.4 to 8.2 and now get following error message:

Error source:
```
/var/www/grocy/services/DatabaseService.php:42
```

Error message:
```
SQLSTATE[23000]: Integrity constraint violation: 19 Unsupported product nesting level detected (currently only 1 level is supported)
```

Stack trace:
```
#0 /var/www/grocy/services/DatabaseService.php(42): PDO->exec()
#1 /var/www/grocy/services/DatabaseMigrationService.php(69): Grocy\Services\DatabaseService->ExecuteDbStatement()
#2 /var/www/grocy/services/DatabaseMigrationService.php(35): Grocy\Services\DatabaseMigrationService->ExecuteSqlMigrationWhenNeeded()
#3 /var/www/grocy/controllers/SystemController.php(30): Grocy\Services\DatabaseMigrationService->MigrateDatabase()
#4 /var/www/grocy/packages/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): Grocy\Controllers\SystemController->Root()
#5 /var/www/grocy/packages/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse->__invoke()
#6 /var/www/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle()
#7 /var/www/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\MiddlewareDispatcher->handle()
#8 /var/www/grocy/packages/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle()
#9 /var/www/grocy/packages/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run()
#10 /var/www/grocy/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#11 /var/www/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\LocaleMiddleware->__invoke()
#12 /var/www/grocy/middleware/AuthMiddleware.php(32): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#13 /var/www/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\AuthMiddleware->__invoke()
#14 /var/www/grocy/packages/slim/slim/Slim/Middleware/RoutingMiddleware.php(45): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#15 /var/www/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\RoutingMiddleware->process()
#16 /var/www/grocy/packages/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#17 /var/www/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process()
#18 /var/www/grocy/middleware/CorsMiddleware.php(27): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /var/www/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\CorsMiddleware->__invoke()
#20 /var/www/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /var/www/grocy/packages/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle()
#22 /var/www/grocy/packages/slim/slim/Slim/App.php(183): Slim\App->handle()
#23 /var/www/grocy/app.php(112): Slim\App->run()
#24 /var/www/grocy/public/index.php(45): require_once('...')
#25 {main}
```

System info:
```
{
    "grocy_version": {
        "Version": "4.2.0",
        "ReleaseDate": "2024-03-15"
    },
    "php_version": "8.2.19",
    "sqlite_version": "3.40.1",
    "os": "Linux 6.5.13-5-pve #1 SMP PREEMPT_DYNAMIC PMX 6.5.13-5 (2024-04-05T11:03Z) x86_64",
    "client": "Mozilla\/5.0 (X11; Linux x86_64; rv:109.0) Gecko\/20100101 Firefox\/115.0"
}
```

**Comment by berrnd** [comment]
Please do a quick and easy search before opening new requests.

See #1636, #1550 and #1542. Check and try what's mentioned there and if you really think this is something new not solvable on your end, then please provide a 100 % reproducible example - I really can't guess all the details, sorry.
