### ISSUE TITLE
Bug: Crash while typing text in the name field after scanning a barcode during the purchase process

### ISSUE THREAD

**Issue by k3a** [grocy/grocy#2583]
Version 3.5.2 installed from F-Droid.
Samsung Galaxy S21 5G international, android 14.

After holding the Scan icon on the main screen to enter purchase mode, a field appears to enter a name. When I type text quickly, it responds quite slowly, and after typing more, it sometimes crashes with the following stack trace:

```
09-26 16:27:42.710  3094  3094 E AndroidRuntime: FATAL EXCEPTION: main
09-26 16:27:42.710  3094  3094 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 3094
09-26 16:27:42.710  3094  3094 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionItemViewHolder{d7ab05 position=1522 id=-1, oldPos=1556, pLpos:1519 scrap [attachedScrap] tmpDetached not recyclable(1) no parent} androidx.recyclerview.widget.RecyclerView{70e9f2b VFED.V... ......ID 0,672-1080,258796 #7f0b03e7 app:id/recycler}, adapter:xyz.zedler.patrick.grocy.adapter.ChooseProductAdapter@ac0feab, layout:androidx.recyclerview.widget.LinearLayoutManager@417b8e3, context:xyz.zedler.patrick.grocy.activity.SplashActivity@9ae0952
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:603)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:63)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:49)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:800)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:74)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:64)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.view.View.measure(View.java:28571)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.view.View.measure(View.java:28571)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:423)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.measure(BasicMeasure.java:93)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1211)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:246)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.view.View.measure(View.java:28571)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at androidx.core.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:39)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at androidx.core.widget.NestedScrollView.onMeasure(NestedScrollView.java:1)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.view.View.measure(View.java:28571)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.view.View.measure(View.java:28571)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at xyz.zedler.patrick.grocy.view.swiperefreshlayout.CustomSwipeRefreshLayout.onMeasure(CustomSwipeRefreshLayout.java:54)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.view.View.measure(View.java:28571)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:428)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.view.View.measure(View.java:28571)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.view.View.measure(View.java:28571)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.view.View.measure(View.java:28571)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:428)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.view.View.measure(View.java:28571)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:160)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.view.View.measure(View.java:28571)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.view.View.measure(View.java:28571)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.view.View.measure(View.java:28571)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.view.View.measure(View.java:28571)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1036)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.view.View.measure(View.java:28571)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:5203)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3603)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3973)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3288)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11344)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1689)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:1153)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:1079)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:958)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:230)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:319)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8919)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
09-26 16:27:42.710  3094  3094 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

I have no idea why this happens, but perhaps someone else will know.

It would also be helpful if the response time could be sped up, or at least if a debounce of 1 or 2 seconds could be added. By that, I mean waiting for a short period after the last character is typed before making a query to the server. There is no need to query after each character when typing quickly.

**Comment by berrnd** [comment]
Grocy is a web application, not an android app.

None of the community contributed apps/tools/integrations are maintained here.
