### ISSUE TITLE
Bug: Click on Menu-Item „Shopping List“ Results in Error

### ISSUE THREAD

**Issue by HartwigHuebner** [grocy/grocy#2622]

**Comment by berrnd** [comment]
🙄

Zero description = zero help possible.

**Comment by HartwigHuebner** [comment]
Error is reproducible and Error description and Error source was sent. What Else do you require?

**Comment by HartwigHuebner** [comment]
GitHub obviously did not take the information I entered:
I use iOS devices (several)
Setup: Grocy AddOn for Homeassistant;

I click on “Einkaufzettel”/“Shoppinglist” and receive the following error message:
Error source:
```
/data/grocy/viewcache/fbf71db0bf421e50b4f55fb6c45f4d10.php:254
```

Error message:
```
Unsupported operand types: string * string (View: /var/www/grocy/views/shoppinglist.blade.php)
```

Stack trace:
```
#0 /var/www/grocy/packages/illuminate/view/Engines/PhpEngine.php(60): Illuminate\View\Engines\CompilerEngine->handleViewException()
#1 /var/www/grocy/packages/illuminate/view/Engines/CompilerEngine.php(72): Illuminate\View\Engines\PhpEngine->evaluatePath()
#2 /var/www/grocy/packages/illuminate/view/View.php(207): Illuminate\View\Engines\CompilerEngine->get()
#3 /var/www/grocy/packages/illuminate/view/View.php(190): Illuminate\View\View->getContents()
#4 /var/www/grocy/packages/illuminate/view/View.php(159): Illuminate\View\View->renderContents()
#5 /var/www/grocy/packages/berrnd/slim-blade-view/src/Blade.php(173): Illuminate\View\View->render()
#6 /var/www/grocy/packages/berrnd/slim-blade-view/src/Blade.php(65): Slim\Views\Blade->fetch()
#7 /var/www/grocy/controllers/BaseController.php(186): Slim\Views\Blade->render()
#8 /var/www/grocy/controllers/BaseController.php(209): Grocy\Controllers\BaseController->render()
#9 /var/www/grocy/controllers/StockController.php(395): Grocy\Controllers\BaseController->renderPage()
#10 /var/www/grocy/packages/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): Grocy\Controllers\StockController->ShoppingList()
#11 /var/www/grocy/packages/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse->__invoke()
#12 /var/www/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle()
#13 /var/www/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\MiddlewareDispatcher->handle()
#14 /var/www/grocy/packages/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle()
#15 /var/www/grocy/packages/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run()
#16 /var/www/grocy/middleware/LocaleMiddleware.php(16): Slim\Routing\RouteRunner->handle()
#17 /var/www/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\LocaleMiddleware->__invoke()
#18 /var/www/grocy/middleware/AuthMiddleware.php(77): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /var/www/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\AuthMiddleware->__invoke()
#20 /var/www/grocy/packages/slim/slim/Slim/Middleware/RoutingMiddleware.php(45): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /var/www/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\RoutingMiddleware->process()
#22 /var/www/grocy/packages/slim/slim/Slim/Middleware/ErrorMiddleware.php(76): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#23 /var/www/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(121): Slim\Middleware\ErrorMiddleware->process()
#24 /var/www/grocy/middleware/CorsMiddleware.php(27): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#25 /var/www/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(269): Grocy\Middleware\CorsMiddleware->__invoke()
#26 /var/www/grocy/packages/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#27 /var/www/grocy/packages/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle()
#28 /var/www/grocy/packages/slim/slim/Slim/App.php(183): Slim\App->handle()
#29 /var/www/grocy/app.php(112): Slim\App->run()
#30 /var/www/grocy/public/index.php(45): require_once('...')
#31 {main}
```

System info:
```
{
    "grocy_version": {
        "Version": "4.2.0",
        "ReleaseDate": "2024-03-15"
    },
    "php_version": "8.2.20",
    "sqlite_version": "3.44.2",
    "os": "Linux 6.6.51-haos-raspi #1 SMP PREEMPT Tue Dec  3 19:23:02 UTC 2024 aarch64",
    "client": "Mozilla\/5.0 (iPad; CPU OS 18_1_1 like Mac OS X) AppleWebKit\/605.1.15 (KHTML, like Gecko) Home Assistant\/2024.9.4 (io.robbie.HomeAssistant; build:2024.905; iPadOS 18.1.1) Mobile\/HomeAssistant, like Safari"
}
```

**Comment by berrnd** [comment]
This is what you sent:

![grafik](https://github.com/user-attachments/assets/5ce4b6ac-cd61-4a01-9f46-b5897d5cf5e8)

> Error is reproducible

The issue template clearly mentions to provide all the steps required to reproduce a problem, ideally recreate the corresponding scenario on a [persistent demo instance](https://www.reddit.com/r/grocy/comments/jwnk9b).

Clicking on "Shopping List" there doesn't result in an error:

https://github.com/user-attachments/assets/ed005a87-9e61-43f5-9b72-d380983a651f

You waste my time. Merry Christmas.

**Comment by berrnd** [comment]
I've added #2657 which tracks to finally prevent this old mystery obviously not solvable at the origin source (since years).
