### ISSUE TITLE
Call to undefined function Illuminate\View\Compilers\token_get_all()

### ISSUE THREAD

**Issue by raimundomartins** [grocy/grocy#344]
I'm trying to setup grocy on my server but I get this error:

```
Slim Application Error

The application could not run because of the following error:
Details
Type: Error
Message: Call to undefined function Illuminate\View\Compilers\token_get_all()
File: /srv/grocy/vendor/illuminate/view/Compilers/BladeCompiler.php
Line: 204
Trace

#0 /srv/grocy/vendor/illuminate/view/Compilers/BladeCompiler.php(123): Illuminate\View\Compilers\BladeCompiler->compileString('@extends('layou...')
#1 /srv/grocy/vendor/illuminate/view/Engines/CompilerEngine.php(51): Illuminate\View\Compilers\BladeCompiler->compile('/srv/grocy/view...')
#2 /srv/grocy/vendor/illuminate/view/View.php(142): Illuminate\View\Engines\CompilerEngine->get('/srv/grocy/view...', Array)
#3 /srv/grocy/vendor/illuminate/view/View.php(125): Illuminate\View\View->getContents()
#4 /srv/grocy/vendor/illuminate/view/View.php(90): Illuminate\View\View->renderContents()
#5 /srv/grocy/vendor/rubellum/slim-blade-view/src/Blade.php(173): Illuminate\View\View->render()
#6 /srv/grocy/vendor/rubellum/slim-blade-view/src/Blade.php(65): Slim\Views\Blade->fetch('login', Array)
#7 /srv/grocy/controllers/LoginController.php(57): Slim\Views\Blade->render(Object(Slim\Http\Response), 'login')
#8 [internal function]: Grocy\Controllers\LoginController->LoginPage(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#9 /srv/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#10 /srv/grocy/vendor/slim/slim/Slim/Route.php(356): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#11 /srv/grocy/middleware/SessionAuthMiddleware.php(57): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#12 [internal function]: Grocy\Middleware\SessionAuthMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#13 /srv/grocy/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Grocy\Middleware\SessionAuthMiddleware), Array)
#14 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#15 /srv/grocy/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#16 /srv/grocy/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#17 /srv/grocy/vendor/slim/slim/Slim/Route.php(334): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#18 /srv/grocy/vendor/slim/slim/Slim/App.php(515): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#19 /srv/grocy/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#20 /srv/grocy/vendor/slim/slim/Slim/App.php(405): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#21 /srv/grocy/vendor/slim/slim/Slim/App.php(313): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#22 /srv/grocy/app.php(80): Slim\App->run()
#23 /srv/grocy/public/index.php(3): require_once('/srv/grocy/app....')
#24 {main}
```

I should note I'm running it under location /hrp instead of. I have `Setting('BASE_URL', 'https://myserver.tld/hrp');` in `data/config.php` and here's the relevant nginx.conf part

```
        location /hrp/ {
                root /srv/grocy/public;
                index index.php;
                try_files $uri /hrp/index.php;
        }

        location ~* /hrp/.*\.php$ {
                root /srv/grocy/public;
                fastcgi_pass unix:/run/grocy/grocy.socket;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_index index.php;
                include fastcgi_params;
        }
```

**Comment by raimundomartins** [comment]
Sorry, it appears this is solved by installing php7-tokenizer (on Alpine). Maybe you can see this as a docs bug :stuck_out_tongue: 
By the way, I also needed to install php7-pdo_sqlite (not just sqlite3)
Everything seems to be working, thanks for the great app! :smile:

**Comment by berrnd** [comment]
Ok, great that you found it immediately yourself... :)

But I think the need to have the PHP PDO-SQLite extension installed is just normal, the (system) sqlite3 has nothing to do with PHP...
And that this is required is [mentioned in README](https://github.com/grocy/grocy#how-to-install)...

**Comment by raimundomartins** [comment]
> the (system) sqlite3 has nothing to do with PHP

I am starting to see that pattern now. This is my first deployment of a php app not managed by distribution packages, so I had some difficulties.
