### ISSUE TITLE
How to install inside LXC container (Alpine Linux)

### ISSUE THREAD

**Issue by jose1711** [grocy/grocy#523]
# How to install grocy on Alpine Linux (running inside LXC container

Alpine is a minimalistic Linux distributions often being containerized inside Docker or LXC. The guide assumes you're following the steps below a fresh Alpine Linux installation, all commands are to be run under `root` user. The whole LXC container takes less than 200 MB.

`grocy` is configured to be served on HTTP (port 80) and hence only LAN (where everyone is trusted) is assumed.

Parts of these instructions are taken from Alpine Wiki (https://wiki.alpinelinux.org/wiki/Nginx).

## Pull latest packages
```
apk update
apk upgrade
```

## Install dependencies (`nginx` + `php` + `php sqlite`)
```
apk add php nginx php7-sqlite3 php7-fpm php7-pdo_sqlite php7-gd php7-fileinfo php7-tokenizer 
```

## Create a dedicated user/group for `nginx`
```
adduser -D -g 'www' www
```

## Configure `nginx`
```
cat > /etc/nginx/nginx.conf <<HERE
user                            www;
worker_processes                auto; # it will be determinate automatically by the number of cores

error_log                       /var/log/nginx/error.log warn;

events {
    worker_connections          1024;
}

http {
    include                     /etc/nginx/mime.types;
    default_type                application/octet-stream;
    sendfile                    on;
    access_log                  /var/log/nginx/access.log;
    keepalive_timeout           3000;
    server {
        listen                  80;
        root                    /www/public;
        index                   index.html index.htm index.php;
        try_files               \$uri /index.php;
        server_name             localhost;
        client_max_body_size    32m;
        error_page              500 502 503 504  /50x.html;
        location = /50x.html {
              root              /var/lib/nginx/html;
        }
        location ~ \.php\$ {
              fastcgi_pass      127.0.0.1:9000;
              fastcgi_index     index.php;
              include           fastcgi.conf;
        }
    }
}
HERE
```

## Create webroot
```
mkdir /www
chown -R www:www /var/lib/nginx
chown www:www /var/tmp/nginx
```

## Configure `php`
```
PHP_FPM_USER="www"
PHP_FPM_GROUP="www"
PHP_FPM_LISTEN_MODE="0660"
PHP_MEMORY_LIMIT="512M"
PHP_MAX_UPLOAD="50M"
PHP_MAX_FILE_UPLOAD="200"
PHP_MAX_POST="100M"
PHP_DISPLAY_ERRORS="On"
PHP_DISPLAY_STARTUP_ERRORS="On"
PHP_ERROR_REPORTING="E_COMPILE_ERROR\|E_RECOVERABLE_ERROR\|E_ERROR\|E_CORE_ERROR"
PHP_CGI_FIX_PATHINFO=0
sed -i "s|;listen.owner\s*=\s*nobody|listen.owner = ${PHP_FPM_USER}|g" /etc/php7/php-fpm.d/www.conf
sed -i "s|;listen.group\s*=\s*nobody|listen.group = ${PHP_FPM_GROUP}|g" /etc/php7/php-fpm.d/www.conf
sed -i "s|;listen.mode\s*=\s*0660|listen.mode = ${PHP_FPM_LISTEN_MODE}|g" /etc/php7/php-fpm.d/www.conf
sed -i "s|user\s*=\s*nobody|user = ${PHP_FPM_USER}|g" /etc/php7/php-fpm.d/www.conf
sed -i "s|group\s*=\s*nobody|group = ${PHP_FPM_GROUP}|g" /etc/php7/php-fpm.d/www.conf
sed -i "s|;log_level\s*=\s*notice|log_level = notice|g" /etc/php7/php-fpm.d/www.conf
sed -i "s|display_errors\s*=\s*Off|display_errors = ${PHP_DISPLAY_ERRORS}|i" /etc/php7/php.ini
sed -i "s|display_startup_errors\s*=\s*Off|display_startup_errors = ${PHP_DISPLAY_STARTUP_ERRORS}|i" /etc/php7/php.ini
sed -i "s|error_reporting\s*=\s*E_ALL & ~E_DEPRECATED & ~E_STRICT|error_reporting = ${PHP_ERROR_REPORTING}|i" /etc/php7/php.ini
sed -i "s|;*memory_limit =.*|memory_limit = ${PHP_MEMORY_LIMIT}|i" /etc/php7/php.ini
sed -i "s|;*upload_max_filesize =.*|upload_max_filesize = ${PHP_MAX_UPLOAD}|i" /etc/php7/php.ini
sed -i "s|;*max_file_uploads =.*|max_file_uploads = ${PHP_MAX_FILE_UPLOAD}|i" /etc/php7/php.ini
sed -i "s|;*post_max_size =.*|post_max_size = ${PHP_MAX_POST}|i" /etc/php7/php.ini
sed -i "s|;*cgi.fix_pathinfo=.*|cgi.fix_pathinfo= ${PHP_CGI_FIX_PATHINFO}|i" /etc/php7/php.ini
sed -i "s|;extension=fileinfo|extension=fileinfo|" /etc/php7/php.ini
sed -i "s|;extension=gd2|extension=gd2|" /etc/php7/php.ini
sed -i "s|;extension=pdo_sqlite|extension=pdo_sqlite|" /etc/php7/php.ini
sed -i "s|;extension=sqlite3|extension=sqlite3|" /etc/php7/php.ini
```

## Get and extract `grocy` to webroot
```
# Adjust `ver` to (preferrably) the latest version found at https://github.com/grocy/grocy/releases
cd /www
pkgver=2.5.2
wget https://github.com/grocy/grocy/releases/download/v${pkgver}/grocy_${pkgver}.zip

unzip grocy_${pkgver}.zip
rm grocy_${pkgver}.zip
```

## Adjust `grocy` configuration, set correct permissions
```
cp config-dist.php data/config.php
# edit data/config.php (language, menu items, currency, etc)
chown -R www:www /www
```

## Start php-fpm and enable it after boot
```
rc-service php-fpm7 start
rc-update add php-fpm7 default
```

## Start nginx and enable it after boot
```
rc-service nginx start
rc-update add nginx default
```

```
test access to grocy in your browser
reboot server to check whether services are correctly started
```

# Setup a regular backup of `config.php`, `/www/data/grocy.db` and `/www/data/storage`
```
tar cvzf /www/backup.tgz /www/data/config.php /www/data/grocy.db /www/data/storage
cp /www/backup.tgz SOME_PLACE_SAFE
# where SOME_PLACE_SAFE is probably a mount from a remote system
```

## Troubleshooting
Check logs
```
tail -f /var/log/nginx/access.log
tail -f /var/log/nginx/error.log
tail -f /var/log/php7/error.log
```

**Comment by berrnd** [comment]
Thank you for this guide! :)

I will add a link to this issue on https://grocy.info/links.

**Comment by garrettdowd** [comment]
Followed the steps in this tutorial and could not get Grocy up an running. Not sure where to go from here.

- Proxmox LXC - Alpine 3.9
- Unprivileged
- Tried both Grocy v2.5.2 and the current version 2.6.0/

Error as server by the browser http://[LXC_IP]:80
```
Fatal error: Uncaught Error: Call to undefined function LessQL\json_encode() in /www/vendor/morris/lessql/src/LessQL/Result.php:662 Stack trace: #0 /www/vendor/morris/lessql/src/LessQL/Result.php(137): LessQL\Result->getDefinition() #1 /www/vendor/morris/lessql/src/LessQL/Result.php(334): LessQL\Result->execute() #2 /www/services/LocalizationService.php(60): LessQL\Result->fetchAll() #3 /www/services/LocalizationService.php(18): Grocy\Services\LocalizationService->LoadLocalizations('en') #4 /www/controllers/BaseController.php(16): Grocy\Services\LocalizationService->__construct('en') #5 /www/controllers/LoginController.php(13): Grocy\Controllers\BaseController->__construct(Object(Slim\Container)) #6 /www/app.php(64): Grocy\Controllers\LoginController->__construct(Object(Slim\Container), 'grocy_session') #7 /www/vendor/pimple/pimple/src/Pimple/Container.php(118): {closure}(Object(Slim\Container)) #8 /www/vendor/slim/slim/Slim/Container.php(108): Pimple\Container->offsetGet('LoginController...') #9 /www/vendor/slim/slim/Sli in /www/vendor/morris/lessql/src/LessQL/Result.php on line 662
```

```
grocy:/www# tail -f /var/log/nginx/error.log
Stack trace:
#0 /www/vendor/morris/lessql/src/LessQL/Result.php(137): LessQL\Result->getDefinition()
#1 /www/vendor/morris/lessql/src/LessQL/Result.php(334): LessQL\Result->execute()
#2 /www/services/LocalizationService.php(60): LessQL\Result->fetchAll()
#3 /www/services/LocalizationService.php(18): Grocy\Services\LocalizationService->LoadLocalizations('en')
#4 /www/controllers/BaseController.php(16): Grocy\Services\LocalizationService->__construct('en')
#5 /www/controllers/LoginController.php(13): Grocy\Controllers\BaseController->__construct(Object(Slim\Container))
#6 /www/app.php(64): Grocy\Controllers\LoginController->__construct(Object(Slim\Container), 'grocy_session')
#7 /www/vendor/pimple/pimple/src/Pimple/Container.php(118): {closure}(Object(Slim\Container))
#8 /www/vendor/slim/slim/Slim/Container.php(108): Pimple\Container->offsetGet('LoginControlle" while reading response header from upstream, client: 192.168.0.206, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.0.207"
```

**Comment by jose1711** [comment]
Please try installing `composer` and report back.
```
apk add composer
```

**Comment by garrettdowd** [comment]
> 
> 
> Please try installing `composer` and report back.
> 
> ```
> apk add composer
> ```

That worked. Thanks for the quick reply and the great install guide!

**Comment by jose1711** [comment]
Thank you for the report, this package somehow slipped from the guide -- this is now fixed.

**Comment by emk2203** [comment]
Does this work with 2.6.1? My own howto for an Ubuntu minimal install ceased working after the change from 2.6.0 to 2.6.1.

**Comment by jose1711** [comment]
I don't think there are major differences between 2.6.0 and 2.6.1. What got broken on Ubuntu?

**Comment by emk2203** [comment]
2.6.1 introduced v4 of the Slim framework, while 2.6.0 had v3. This leads to the installation failing as in #623 . I posted my howto in #201 and cannot get it to work anymore either, failing with exactly the same error as in #623.

I tried with and without subdirectories and subdomains, but no dice.

**Comment by jose1711** [comment]
Thank you, I was able to install 2.6.1 using the steps above without a problem.

**Comment by emk2203** [comment]
Good to know. I try to update my instructions as well, it's a big help to see that your version works.

**Comment by emk2203** [comment]
I also got my instructions in #201 to work, but only under webroot. I am going to update my instructions accordingly. Thanks again, it was a big help to see that yours worked!

**Comment by Konradrundfunk** [comment]
How can I get https to work I need it in order to scan the items

**Comment by garrettdowd** [comment]
> 
> 
> How can I get https to work I need it in order to scan the items

HTTPS/SSL is not related to installing inside a LXC. You should find another related issue or open a new issue. That being said, one way of enabling HTTPS is through a reverse proxy (NGINX/Traefik). I am sure you can receive further help if you post in a more closely related issue.

**Comment by chrispratl** [comment]
I just ran into a little problem when using this guide: I tried to login with the default user and it hit an error: There is a reference to `ctype_space` function which is not defined.
Google helped me out on this one and advised me to `apk add php7-ctype`. Now everything works fine. This package is not mentioned in the guide - maybe you could add it?

Versions: Alpine 3.12.3 (latest at the time of writing, I think) and Grocy 3.0.0 (also the latest one).

Thanks for the guide!

**Comment by jose1711** [comment]
@chrispratl Thank you, Chris, updated!

**Comment by witzker** [comment]
Hi
Will this guide also work on a VM on ESXI 7 with Alpine 3.13.4 and Grocy 3.0.1 ?
If not can You Pls. provide one?
I will help testing.

**Comment by infinitytec** [comment]
I seem to be getting this error on the webpage:
`
Fatal error: Uncaught Error: Call to undefined function LessQL\json_encode() in /www/vendor/morris/lessql/src/LessQL/Result.php:662 Stack trace: #0 /www/vendor/morris/lessql/src/LessQL/Result.php(137): LessQL\Result->getDefinition() #1 /www/vendor/morris/lessql/src/LessQL/Result.php(334): LessQL\Result->execute() #2 /www/services/LocalizationService.php(60): LessQL\Result->fetchAll() #3 /www/services/LocalizationService.php(18): Grocy\Services\LocalizationService->LoadLocalizations() #4 /www/controllers/BaseController.php(16): Grocy\Services\LocalizationService->__construct() #5 /www/controllers/LoginController.php(13): Grocy\Controllers\BaseController->__construct() #6 /www/app.php(64): Grocy\Controllers\LoginController->__construct() #7 /www/vendor/pimple/pimple/src/Pimple/Container.php(118): {closure}() #8 /www/vendor/slim/slim/Slim/Container.php(108): Pimple\Container->offsetGet() #9 /www/vendor/slim/slim/Slim/Container.php(162): Slim\Container->get() #10 /www/routes.php(120): Slim\Container->__get() #11 /www/app.php( in /www/vendor/morris/lessql/src/LessQL/Result.php on line 662`

Using Alpine 3.15 on Proxmox 7.1-12

**Comment by KrumbEMT** [comment]
I'm having an issue installing following this guide with 3.3.2. I realize it's related to PHP 8 being required after Grocy v3.1, but I can't figure out the commands to make it play nice. Could it be updated for v3+ ?

**Comment by raverydavis** [comment]
Ansible Playbook that installs 3.3.2
```
- name: "Install Grocy - https://github.com/grocy/grocy/"
  hosts: test
  gather_facts: false
  vars:
    repository: "community"
    grocy_version: "3.3.2"

  pre_tasks:
    - name: Adding edge repo
      command: grep -qxF 'http://dl-cdn.alpinelinux.org/alpine/edge/{{ repository }}' /etc/apk/repositories || echo 'http://dl-cdn.alpinelinux.org/alpine/edge/{{ repository }}' >> /etc/apk/repositories
    - name: Add pkg
      command: apk add php82 nginx composer php82-sqlite3 php82-fpm php82-pdo_sqlite php82-gd php82-fileinfo php82-tokenizer php82-ctype php82-intl php82-mbstring php82-iconv
    - name: Adduser nginx
      command: adduser -D -g 'www' www
    - name: Configure nginx
      shell: |
        cat > /etc/nginx/nginx.conf <<HERE
        user                            www;
        worker_processes                auto; # it will be determinate automatically by the number of cores

        error_log                       /var/log/nginx/error.log warn;

        events {
            worker_connections          1024;
        }

        http {
            include                     /etc/nginx/mime.types;
            default_type                application/octet-stream;
            sendfile                    on;
            access_log                  /var/log/nginx/access.log;
            keepalive_timeout           3000;
            server {
                listen                  80;
                root                    /www/public;
                index                   index.html index.htm index.php;
                try_files               \$uri /index.php;
                server_name             localhost;
                client_max_body_size    32m;
                error_page              500 502 503 504  /50x.html;
                location = /50x.html {
                      root              /var/lib/nginx/html;
                }
                location ~ \.php\$ {
                      fastcgi_pass      127.0.0.1:9000;
                      fastcgi_index     index.php;
                      include           fastcgi.conf;
                }
            }
        }
        HERE
    - name: Create webroot
      shell: |
        mkdir /www
        chown -R www:www /var/lib/nginx
        mkdir /var/tmp/nginx
        chown www:www /var/tmp/nginx
    - name: Configure PHP
      shell: |
        PHP_FPM_USER="www"
        PHP_FPM_GROUP="www"
        PHP_FPM_LISTEN_MODE="0660"
        PHP_MEMORY_LIMIT="512M"
        PHP_MAX_UPLOAD="50M"
        PHP_MAX_FILE_UPLOAD="200"
        PHP_MAX_POST="100M"
        PHP_DISPLAY_ERRORS="On"
        PHP_DISPLAY_STARTUP_ERRORS="On"
        PHP_ERROR_REPORTING="E_COMPILE_ERROR\|E_RECOVERABLE_ERROR\|E_ERROR\|E_CORE_ERROR"
        PHP_CGI_FIX_PATHINFO=0
        sed -i "s|;listen.owner\s*=\s*nobody|listen.owner = ${PHP_FPM_USER}|g" /etc/php82/php-fpm.d/www.conf
        sed -i "s|;listen.group\s*=\s*nobody|listen.group = ${PHP_FPM_GROUP}|g" /etc/php82/php-fpm.d/www.conf
        sed -i "s|;listen.mode\s*=\s*0660|listen.mode = ${PHP_FPM_LISTEN_MODE}|g" /etc/php82/php-fpm.d/www.conf
        sed -i "s|user\s*=\s*nobody|user = ${PHP_FPM_USER}|g" /etc/php82/php-fpm.d/www.conf
        sed -i "s|group\s*=\s*nobody|group = ${PHP_FPM_GROUP}|g" /etc/php82/php-fpm.d/www.conf
        sed -i "s|;log_level\s*=\s*notice|log_level = notice|g" /etc/php82/php-fpm.d/www.conf
        sed -i "s|display_errors\s*=\s*Off|display_errors = ${PHP_DISPLAY_ERRORS}|i" /etc/php82/php.ini
        sed -i "s|display_startup_errors\s*=\s*Off|display_startup_errors = ${PHP_DISPLAY_STARTUP_ERRORS}|i" /etc/php82/php.ini
        sed -i "s|error_reporting\s*=\s*E_ALL & ~E_DEPRECATED & ~E_STRICT|error_reporting = ${PHP_ERROR_REPORTING}|i" /etc/php82/php.ini
        sed -i "s|;*memory_limit =.*|memory_limit = ${PHP_MEMORY_LIMIT}|i" /etc/php82/php.ini
        sed -i "s|;*upload_max_filesize =.*|upload_max_filesize = ${PHP_MAX_UPLOAD}|i" /etc/php82/php.ini
        sed -i "s|;*max_file_uploads =.*|max_file_uploads = ${PHP_MAX_FILE_UPLOAD}|i" /etc/php82/php.ini
        sed -i "s|;*post_max_size =.*|post_max_size = ${PHP_MAX_POST}|i" /etc/php82/php.ini
        sed -i "s|;*cgi.fix_pathinfo=.*|cgi.fix_pathinfo= ${PHP_CGI_FIX_PATHINFO}|i" /etc/php82/php.ini
        sed -i "s|;extension=fileinfo|extension=fileinfo|" /etc/php82/php.ini
        sed -i "s|;extension=gd2|extension=gd2|" /etc/php82/php.ini
        sed -i "s|;extension=pdo_sqlite|extension=pdo_sqlite|" /etc/php82/php.ini
        sed -i "s|;extension=sqlite3|extension=sqlite3|" /etc/php82/php.ini

    - name: Download grocy
      shell: |
        cd /www
        wget https://github.com/grocy/grocy/releases/download/v{{ grocy_version }}/grocy_{{ grocy_version }}.zip
        unzip grocy_{{ grocy_version }}.zip
        rm grocy_{{ grocy_version }}.zip
    - name: Php boot
      shell: |
        rc-service php-fpm82 start
        rc-update add php-fpm82
    - name: Nginx boot
      shell: |
        rc-service nginx start
        rc-update add nginx
    - name: Grocy config
      shell: |
        cp /www/config-dist.php /www/data/config.php
        chown -R www:www /www
    - name: Reboot container
      command: reboot
```

It's the original flow verbatim, so it should work if you don't use Ansible.
