### ISSUE TITLE
Calendar: sharing (iCal) fails with internal server error

### ISSUE THREAD

**Issue by kotnik** [grocy/grocy#730]
Grocy version: 2.6.2

While on Calendar clicking Share/Integrate calendar (iCal) fails with Slim Internal Server Error. This is response from URL `https://GROCY.URL/api/calendar/ical/sharing-link`:

```
Slim Application Error

The application could not run because of the following error:
Details
Type: Error
Code: 0
Message: Class 'Grocy\Controllers\ApiKeyService' not found
File: /var/www/controllers/CalendarApiController.php
Line: 55
Trace

#0 /var/www/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\Controllers\CalendarApiController->IcalSharingLink(Object(Slim\Http\ServerRequest), Object(Slim\Http\Response), Array)
#1 /var/www/vendor/slim/slim/Slim/Routing/Route.php(381): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\ServerRequest), Object(Slim\Http\Response), Array)
#2 /var/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle(Object(Slim\Http\ServerRequest))
#3 /var/www/vendor/tuupola/cors-middleware/src/CorsMiddleware.php(113): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#4 /var/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Tuupola\Middleware\CorsMiddleware->process(Object(Slim\Http\ServerRequest), Object(Slim\MiddlewareDispatcher))
#5 /var/www/middleware/JsonMiddleware.php(13): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#6 /var/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(188): Grocy\Middleware\JsonMiddleware->__invoke(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#7 /var/www/middleware/ApiKeyAuthMiddleware.php(99): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#8 /var/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(283): Grocy\Middleware\ApiKeyAuthMiddleware->__invoke(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#9 /var/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#10 /var/www/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#11 /var/www/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run(Object(Slim\Http\ServerRequest))
#12 /var/www/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(60): Slim\Routing\RouteRunner->handle(Object(Slim\Http\ServerRequest))
#13 /var/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\RoutingMiddleware->process(Object(Slim\Http\ServerRequest), Object(Slim\Routing\RouteRunner))
#14 /var/www/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(98): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#15 /var/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\ErrorMiddleware->process(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#16 /var/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#17 /var/www/vendor/slim/slim/Slim/App.php(211): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#18 /var/www/vendor/slim/slim/Slim/App.php(195): Slim\App->handle(Object(Slim\Http\ServerRequest))
#19 /var/www/app.php(81): Slim\App->run()
#20 /var/www/public/index.php(3): require_once('/var/www/app.ph...')
#21 {main}
```

**Comment by kotnik** [comment]
Reproduced the same issue on [demo site](https://en.demo.grocy.info/calendar).

**Comment by berrnd** [comment]
Please do some searching first...

Already reported and fixed by #669 (still not yet released).

Already mentionend in the preview changelog: https://grocy.info/changelog#preview

Already works on the pre-release demo: https://en.demo-prerelease.grocy.info/calendar

Workaround if you want to have it fixed now already mentioned here: https://www.reddit.com/r/grocy/comments/funiwr/calendar_sharing_not_working/

**Comment by kotnik** [comment]
Thank you for pointers, I didn't know there's pre-release demo (it's not mentioned in the documentation). I'll search more the next time.

**Comment by berrnd** [comment]
No problem at all... :)

> I didn't know there's pre-release demo (it's not mentioned in the documentation)

1. https://github.com/grocy/grocy#give-it-a-try

2. 
![grafik](https://user-images.githubusercontent.com/2161815/79126079-8867d680-7d9f-11ea-8f06-3f6eb321f431.png)
