### ISSUE TITLE
Nginx and subfolder 404 not found 

### ISSUE THREAD

**Issue by yodatak** [grocy/grocy#814]
Hi i use the  configuration here 
https://github.com/grocy/grocy/issues/694#issuecomment-609079721

And i got this error 

And can it be possible in the future or not to make a CI and a default config for nginx for be sure that there is no regrssion in this point 

```
404 Not Found

The application could not run because of the following error:
Details
Type: Slim\Exception\HttpNotFoundException
Code: 404
Message: Not found.
File: /var/www/html/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php
Line: 93
Trace

#0 /var/www/html/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Slim\Middleware\RoutingMiddleware->performRouting(Object(Slim\Http\ServerRequest))
#1 /var/www/html/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\RoutingMiddleware->process(Object(Slim\Http\ServerRequest), Object(Slim\Routing\RouteRunner))
#2 /var/www/html/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#3 /var/www/html/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\ErrorMiddleware->process(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#4 /var/www/html/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#5 /var/www/html/grocy/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#6 /var/www/html/grocy/vendor/slim/slim/Slim/App.php(199): Slim\App->handle(Object(Slim\Http\ServerRequest))
#7 /var/www/html/grocy/app.php(68): Slim\App->run()
#8 /var/www/html/grocy/public/index.php(27): require_once('/var/www/html/g...')
#9 {main}

Go Back
```

**Comment by yodatak** [comment]
My config for exemple 
```
#
# Ansible managed
#

upstream flood {
    server 127.0.0.1:3000 weight=1 ;
}



server {
    listen 80;
    server_name XXXX XXXX;

    root /var/www/html/;
    index index.php index.html index.htm;

    access_log      /var/log/nginx/XXXX.access.log;
    error_log       /var/log/nginx/XXXX.error.log;

        # Use empty location blocks to avoid the redirect for certain requests
        location ~ \.js$ {}
        location ~ \.css$ {}
        location ~ \.woff$ {}
        location ~ \.woff2$ {}
        location ~ \.svg$ {}
        location ~ \.map$ {}



    location / {

    try_files $uri $uri/ /index.php?$args;
    }


    location /grocy  {
           alias /var/www/html/grocy/public;
           try_files $uri $uri/ @grocy;


                       location ~ \.php$ {
                include /etc/nginx/fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $request_filename;
                fastcgi_pass unix:/run/php-fpm/www.sock;
                       }
        }

        location @grocy  {
           rewrite /(.*)$ /grocy/index.php?/$1 last;
        }




    location ~ \.php$ {
        fastcgi_index index.php;
        include /etc/nginx/fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass unix:/run/php-fpm/www.sock;
    }

        location /sonarr {
                proxy_pass http://127.0.0.1:8989;
                proxy_set_header Host localhost;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /radarr {
                proxy_pass http://127.0.0.1:7878;
                proxy_set_header  X-Real-IP  $remote_addr;
                proxy_set_header Host localhost;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header        X-Forwarded-Proto $scheme;
                proxy_redirect off;
        }
        location /lidarr {
                proxy_pass http://127.0.0.1:8686;
                proxy_set_header Host localhost;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /jackett {
                proxy_pass http://127.0.0.1:9117;
                proxy_set_header Host localhost;
        }
        location /flood/ {
          proxy_pass http://127.0.0.1:3000/;
        }
        location /RPC2 {
          scgi_pass   127.0.0.1:5000;
          include     scgi_params;
         }

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }


}

```

**Comment by yodatak** [comment]
and the grocy config 

```
#  => BASE_PATH = /grocy
Setting('BASE_PATH', '/var/www/html/grocy');

# The base url of your installation,
# should be just "/" when running directly under the root of a (sub)domain
# or for example "https://example.com/grocy" when using a subdirectory
Setting('BASE_URL', 'http://XXXX/grocy');

```

**Comment by berrnd** [comment]
Please use the [subreddit](https://www.reddit.com/r/grocy/) for questions/help as [mentioned in README](https://github.com/grocy/grocy#questions--help--bug-reporting--feature-requests), thanks.

And also maybe double check what was discuessed in #694 - for your config, most probably `BASE_PATH` needs to be just `/grocy` (if URL rewriting works, otherwise `/grocy/public/index.php`).

> And can it be possible in the future or not to make a CI and a default config for nginx for be sure that there is no regrssion in this point

Feel free to contribute / setup something for that.
