### ISSUE TITLE
Slim Application Error

### ISSUE THREAD

**Issue by frazzyfin** [grocy/grocy#845]
Upon providing login details to Grocy, I am greeted with a page containing the information below. How can I fix this?

```
Slim Application Error
The application could not run because of the following error:

Details
Type: PDOException
Code: HY000
Message: SQLSTATE[HY000]: General error: 13 database or disk is full
File: /app/grocy/vendor/morris/lessql/src/LessQL/Database.php
Line: 606
Trace
#0 /app/grocy/vendor/morris/lessql/src/LessQL/Database.php(606): PDOStatement->execute()
#1 /app/grocy/vendor/morris/lessql/src/LessQL/Database.php(518): LessQL\Database->insertDefault('sessions', Array)
#2 /app/grocy/vendor/morris/lessql/src/LessQL/Result.php(363): LessQL\Database->insert('sessions', Array, NULL)
#3 /app/grocy/vendor/morris/lessql/src/LessQL/Row.php(261): LessQL\Result->insert(Array)
#4 /app/grocy/vendor/morris/lessql/src/LessQL/Row.php(296): LessQL\Row->save(false)
#5 /app/grocy/services/SessionService.php(57): LessQL\Row->save()
#6 /app/grocy/controllers/LoginController.php(25): Grocy\Services\SessionService->CreateSession('1', false)
#7 /app/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\Controllers\LoginController->ProcessLogin(Object(Slim\Http\ServerRequest), Object(Slim\Http\Response), Array)
#8 /app/grocy/vendor/slim/slim/Slim/Routing/Route.php(381): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\ServerRequest), Object(Slim\Http\Response), Array)
#9 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle(Object(Slim\Http\ServerRequest))
#10 /app/grocy/middleware/SessionAuthMiddleware.php(67): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#11 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(283): Grocy\Middleware\SessionAuthMiddleware->__invoke(Object(Slim\Http\ServerRequest), Object(Slim\MiddlewareDispatcher))
#12 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#13 /app/grocy/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#14 /app/grocy/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run(Object(Slim\Http\ServerRequest))
#15 /app/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(60): Slim\Routing\RouteRunner->handle(Object(Slim\Http\ServerRequest))
#16 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\RoutingMiddleware->process(Object(Slim\Http\ServerRequest), Object(Slim\Routing\RouteRunner))
#17 /app/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#18 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\ErrorMiddleware->process(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#19 /app/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#20 /app/grocy/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#21 /app/grocy/vendor/slim/slim/Slim/App.php(199): Slim\App->handle(Object(Slim\Http\ServerRequest))
#22 /app/grocy/app.php(68): Slim\App->run()
#23 /app/grocy/public/index.php(27): require_once('/app/grocy/app....')
#24 {main}
```

**Comment by frazzyfin** [comment]
Disk was full
